<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Ben Anderson (b.anderson@soton.ac.uk @dataknut)" />


<title>Air Quality in Southampton (UK)</title>

<script src="sccAirQualExplore_covidLockdown2020_files/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="sccAirQualExplore_covidLockdown2020_files/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="sccAirQualExplore_covidLockdown2020_files/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="sccAirQualExplore_covidLockdown2020_files/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="sccAirQualExplore_covidLockdown2020_files/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="sccAirQualExplore_covidLockdown2020_files/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="sccAirQualExplore_covidLockdown2020_files/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="sccAirQualExplore_covidLockdown2020_files/tocify-1.9.1/jquery.tocify.js"></script>
<script src="sccAirQualExplore_covidLockdown2020_files/navigation-1.1/tabsets.js"></script>
<script src="sccAirQualExplore_covidLockdown2020_files/navigation-1.1/codefolding.js"></script>
<link href="sccAirQualExplore_covidLockdown2020_files/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="sccAirQualExplore_covidLockdown2020_files/highlightjs-9.12.0/highlight.js"></script>
<script src="sccAirQualExplore_covidLockdown2020_files/kePrint-0.0.1/kePrint.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>




<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>



<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="fluid-row" id="header">

<div class="btn-group pull-right">
<button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore">Air Quality in Southampton (UK)</h1>
<h3 class="subtitle">Exploring the effect of UK covid 19 lockdown on air quality</h3>
<h4 class="author">Ben Anderson (<a href="mailto:b.anderson@soton.ac.uk">b.anderson@soton.ac.uk</a> <code>@dataknut</code>)</h4>
<h4 class="date">Last run at: 2020-06-18 22:28:33 (Europe/London)</h4>

</div>


<div id="introduction" class="section level1">
<h1><span class="header-section-number">1</span> Introduction</h1>
<p>This report describes exploratory analysis of changes in air quality in the City of Southampton, UK in Spring 2020.</p>
<pre class="r"><code>lastHA &lt;- max(fixedDT[source == &quot;hantsAir&quot;]$dateTimeUTC)
diffHA &lt;- lubridate::now() - lastHA
lastAURN &lt;- max(fixedDT[source == &quot;AURN&quot;]$dateTimeUTC)
diffAURN &lt;- lubridate::now() - lastAURN</code></pre>
<p>Data for Southampton downloaded from :</p>
<ul>
<li><a href="http://www.hantsair.org.uk/hampshire/asp/Bulletin.asp?la=Southampton" class="uri">http://www.hantsair.org.uk/hampshire/asp/Bulletin.asp?la=Southampton</a> (see also <a href="https://www.southampton.gov.uk/environmental-issues/pollution/air-quality/" class="uri">https://www.southampton.gov.uk/environmental-issues/pollution/air-quality/</a>);</li>
<li><a href="https://uk-air.defra.gov.uk/networks/network-info?view=aurn" class="uri">https://uk-air.defra.gov.uk/networks/network-info?view=aurn</a></li>
</ul>
<p>Southampton City Council collects various forms of air quality data at the sites shown in Table <a href="#tab:showSites">2.1</a>. The data is available in raw form from <a href="http://www.hantsair.org.uk/hampshire/asp/Bulletin.asp?la=Southampton&amp;bulletin=daily&amp;site=SH5" class="uri">http://www.hantsair.org.uk/hampshire/asp/Bulletin.asp?la=Southampton&amp;bulletin=daily&amp;site=SH5</a>.</p>
<p>Some of these sites feed data to <a href="https://uk-air.defra.gov.uk/networks/network-info?view=aurn">AURN</a>. The data that goes via AURN is <a href="https://uk-air.defra.gov.uk/assets/documents/Data_Validation_and_Ratification_Process_Apr_2017.pdf">ratified</a> to check for outliers and instrument/measurement error. AURN data less than six months old has not undergone this process. AURN data is (c) Crown 2020 copyright Defra and available for re-use via <a href="https://uk-air.defra.gov.uk" class="uri">https://uk-air.defra.gov.uk</a>, licenced under the <a href="http://www.nationalarchives.gov.uk/doc/open-government-licence/version/2/">Open Government Licence</a> (OGL).</p>
</div>
<div id="data" class="section level1">
<h1><span class="header-section-number">2</span> Data</h1>
<p>In this report we use data from the following sources:</p>
<ul>
<li><a href="http://www.hantsair.org.uk/hampshire/asp/Bulletin.asp?la=Southampton" class="uri">http://www.hantsair.org.uk/hampshire/asp/Bulletin.asp?la=Southampton</a> last updated at 2020-06-08 10:00:00;</li>
<li><a href="https://uk-air.defra.gov.uk/networks/network-info?view=aurn" class="uri">https://uk-air.defra.gov.uk/networks/network-info?view=aurn</a> last updated at 2020-06-07 23:00:00.</li>
</ul>
<p>Table <a href="#tab:showSites">2.1</a> shows the available sites and sources. Note that some of the non-AURN sites appear to have stopped updating recently. For a detailed analysis of recent missing data see Section <a href="#annexMissing">13.1</a>.</p>
<pre class="r"><code>t &lt;- fixedDT[!is.na(value), .(nObs = .N, firstData = min(dateTimeUTC), latestData = max(dateTimeUTC), nMeasures = uniqueN(pollutant)), 
    keyby = .(site, source)]

kableExtra::kable(t, caption = &quot;Sites, data source and number of valid observations. note that measures includes wind speed and direction in the AURN sourced data&quot;, 
    digits = 2) %&gt;% kable_styling()</code></pre>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:showSites">Table 2.1: </span>Sites, data source and number of valid observations. note that measures includes wind speed and direction in the AURN sourced data
</caption>
<thead>
<tr>
<th style="text-align:left;">
site
</th>
<th style="text-align:left;">
source
</th>
<th style="text-align:right;">
nObs
</th>
<th style="text-align:left;">
firstData
</th>
<th style="text-align:left;">
latestData
</th>
<th style="text-align:right;">
nMeasures
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Southampton - A33 Roadside (near docks, AURN site)
</td>
<td style="text-align:left;">
hantsAir
</td>
<td style="text-align:right;">
85918
</td>
<td style="text-align:left;">
2017-01-01 00:00:00
</td>
<td style="text-align:left;">
2020-06-08 10:00:00
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
Southampton - Background (near city centre, AURN site)
</td>
<td style="text-align:left;">
hantsAir
</td>
<td style="text-align:right;">
162148
</td>
<td style="text-align:left;">
2017-01-25 11:00:00
</td>
<td style="text-align:left;">
2020-06-08 10:00:00
</td>
<td style="text-align:right;">
6
</td>
</tr>
<tr>
<td style="text-align:left;">
Southampton - Onslow Road (near RSH)
</td>
<td style="text-align:left;">
hantsAir
</td>
<td style="text-align:right;">
82232
</td>
<td style="text-align:left;">
2017-01-01 00:00:00
</td>
<td style="text-align:left;">
2020-04-15 07:00:00
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
Southampton - Victoria Road (Woolston)
</td>
<td style="text-align:left;">
hantsAir
</td>
<td style="text-align:right;">
60078
</td>
<td style="text-align:left;">
2017-01-01 00:00:00
</td>
<td style="text-align:left;">
2020-04-01 06:00:00
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
Southampton A33 (via AURN)
</td>
<td style="text-align:left;">
AURN
</td>
<td style="text-align:right;">
220010
</td>
<td style="text-align:left;">
2017-01-01 00:00:00
</td>
<td style="text-align:left;">
2020-06-07 23:00:00
</td>
<td style="text-align:right;">
8
</td>
</tr>
<tr>
<td style="text-align:left;">
Southampton Centre (via AURN)
</td>
<td style="text-align:left;">
AURN
</td>
<td style="text-align:right;">
343216
</td>
<td style="text-align:left;">
2017-01-01 00:00:00
</td>
<td style="text-align:left;">
2020-06-07 23:00:00
</td>
<td style="text-align:right;">
13
</td>
</tr>
</tbody>
</table>
<p>Table <a href="#tab:showPollutants">2.2</a> shows the poillutants recorded at each site.</p>
<pre class="r"><code>t &lt;- with(fixedDT[!is.na(value)], table(pollutant, site))

kableExtra::kable(t, caption = &quot;Sites, pollutant and number of valid observations&quot;, digits = 2) %&gt;% kable_styling()</code></pre>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:showPollutants">Table 2.2: </span>Sites, pollutant and number of valid observations
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
Southampton - A33 Roadside (near docks, AURN site)
</th>
<th style="text-align:right;">
Southampton - Background (near city centre, AURN site)
</th>
<th style="text-align:right;">
Southampton - Onslow Road (near RSH)
</th>
<th style="text-align:right;">
Southampton - Victoria Road (Woolston)
</th>
<th style="text-align:right;">
Southampton A33 (via AURN)
</th>
<th style="text-align:right;">
Southampton Centre (via AURN)
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
no
</td>
<td style="text-align:right;">
29055
</td>
<td style="text-align:right;">
28702
</td>
<td style="text-align:right;">
27412
</td>
<td style="text-align:right;">
20026
</td>
<td style="text-align:right;">
29641
</td>
<td style="text-align:right;">
28657
</td>
</tr>
<tr>
<td style="text-align:left;">
no2
</td>
<td style="text-align:right;">
29020
</td>
<td style="text-align:right;">
28702
</td>
<td style="text-align:right;">
27408
</td>
<td style="text-align:right;">
20026
</td>
<td style="text-align:right;">
29640
</td>
<td style="text-align:right;">
28657
</td>
</tr>
<tr>
<td style="text-align:left;">
nox
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
22877
</td>
<td style="text-align:right;">
27412
</td>
<td style="text-align:right;">
20026
</td>
<td style="text-align:right;">
29640
</td>
<td style="text-align:right;">
28658
</td>
</tr>
<tr>
<td style="text-align:left;">
nv10
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
23208
</td>
<td style="text-align:right;">
21105
</td>
</tr>
<tr>
<td style="text-align:left;">
nv2.5
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
22627
</td>
</tr>
<tr>
<td style="text-align:left;">
o3
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
28645
</td>
</tr>
<tr>
<td style="text-align:left;">
pm10
</td>
<td style="text-align:right;">
27843
</td>
<td style="text-align:right;">
26124
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
25681
</td>
<td style="text-align:right;">
26180
</td>
</tr>
<tr>
<td style="text-align:left;">
pm2.5
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
27632
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
27702
</td>
</tr>
<tr>
<td style="text-align:left;">
so2
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
28261
</td>
</tr>
<tr>
<td style="text-align:left;">
sp2
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
28111
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
v10
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
23208
</td>
<td style="text-align:right;">
21105
</td>
</tr>
<tr>
<td style="text-align:left;">
v2.5
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
22627
</td>
</tr>
<tr>
<td style="text-align:left;">
wd
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
29496
</td>
<td style="text-align:right;">
29496
</td>
</tr>
<tr>
<td style="text-align:left;">
ws
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
29496
</td>
<td style="text-align:right;">
29496
</td>
</tr>
</tbody>
</table>
<p>To avoid confusion and 'double counting', in the remainder of the analysis we replace the Southampton AURN site data with the data for the same site sourced via AURN as shown in Table <a href="#tab:selectFinalSites">2.3</a>. This has the disadvantage that the data is slightly less up to date (see Table <a href="#tab:showSites">2.1</a>). As will be explained below in the comparative analysis we will use only the AURN data to avoid missing data issues.</p>
<pre class="r"><code>fixedDT &lt;- fixedDT[!(site %like% &quot;AURN site&quot;)]

t &lt;- fixedDT[!is.na(value), .(nObs = .N, nPollutants = uniqueN(pollutant), lastDate = max(dateTimeUTC)), keyby = .(site, 
    source)]

kableExtra::kable(t, caption = &quot;Sites, data source and number of valid observations&quot;, digits = 2) %&gt;% kable_styling()</code></pre>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:selectFinalSites">Table 2.3: </span>Sites, data source and number of valid observations
</caption>
<thead>
<tr>
<th style="text-align:left;">
site
</th>
<th style="text-align:left;">
source
</th>
<th style="text-align:right;">
nObs
</th>
<th style="text-align:right;">
nPollutants
</th>
<th style="text-align:left;">
lastDate
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Southampton - Onslow Road (near RSH)
</td>
<td style="text-align:left;">
hantsAir
</td>
<td style="text-align:right;">
82232
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:left;">
2020-04-15 07:00:00
</td>
</tr>
<tr>
<td style="text-align:left;">
Southampton - Victoria Road (Woolston)
</td>
<td style="text-align:left;">
hantsAir
</td>
<td style="text-align:right;">
60078
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:left;">
2020-04-01 06:00:00
</td>
</tr>
<tr>
<td style="text-align:left;">
Southampton A33 (via AURN)
</td>
<td style="text-align:left;">
AURN
</td>
<td style="text-align:right;">
220010
</td>
<td style="text-align:right;">
8
</td>
<td style="text-align:left;">
2020-06-07 23:00:00
</td>
</tr>
<tr>
<td style="text-align:left;">
Southampton Centre (via AURN)
</td>
<td style="text-align:left;">
AURN
</td>
<td style="text-align:right;">
343216
</td>
<td style="text-align:right;">
13
</td>
<td style="text-align:left;">
2020-06-07 23:00:00
</td>
</tr>
</tbody>
</table>
<p>We use this data to compare:</p>
<ul>
<li>pre and during-lockdown air quality measures</li>
<li>air quality measures during lockdown 2020 with average measures for the same time periods in the preceding 3 years (2017-2019)</li>
</ul>
<p>It should be noted that air pollution levels in any given period of time are highly dependent on the prevailing meteorological conditions. As a result it can be very difficult to disentangle the affects of a reduction in source strength from the affects of local surface conditions. This is abundantly clear in the analysis which follows given that the Easter weekend was forecast to have <a href="https://airqualitynews.com/2020/04/07/people-at-risk-from-coronavirus-warned-with-very-high-air-pollution-episode-predicted-for-uk/">very high import of pollution from Europe</a> and that the wind direction and speed was highly variable across the lockdown period (see Figure <a href="#fig:recentWind">10.1</a>).</p>
<p>Further, air quality is not wholly driven by sources that lockdown might suppress and indeed that suppression may lead to rebound affects. For example we might expect more emissions due to increased domestic heating during cooler lockdown periods. As a result the analysis presented below must be considered a preliminary ‘before meteorological adjustment’ and ‘before controlling for other sources’ analysis of the affect of lockdown on air quality in Southampton.</p>
<p>For much more detailed analysis see a longer and very messy <a href="https://dataknut.github.io/airQual/sccAirQualExplore_Exploring%20the%20SSC%20and%20AURN%20data.html">data report</a>.</p>
</div>
<div id="who-air-quality-thresholds" class="section level1">
<h1><span class="header-section-number">3</span> WHO air quality thresholds</h1>
<p>A number of the following plots show the relevant WHO air quality thresholds and limits. These are taken from:</p>
<ul>
<li><a href="https://www.who.int/news-room/fact-sheets/detail/ambient-(outdoor)-air-quality-and-health" class="uri">https://www.who.int/news-room/fact-sheets/detail/ambient-(outdoor)-air-quality-and-health</a></li>
</ul>
</div>
<div id="nitrogen-dioxide-no2" class="section level1">
<h1><span class="header-section-number">4</span> Nitrogen Dioxide (no2)</h1>
<pre class="r"><code>yLab &lt;- &quot;Nitrogen Dioxide (ug/m3)&quot;
no2dt &lt;- fixedDT[pollutant == &quot;no2&quot;]</code></pre>
<p>Figure <a href="#fig:theilSenNO2">4.1</a> shows the NO2 trend over time. Is lockdown below trend?</p>
<pre class="r"><code>no2dt[, `:=`(date, as.Date(dateTimeUTC))]  # set date to date for this one

oaNO2 &lt;- openair::TheilSen(no2dt[date &lt; as.Date(&quot;2020-06-01&quot;)], &quot;value&quot;, ylab = &quot;NO2&quot;, deseason = TRUE, xlab = &quot;Year&quot;, 
    date.format = &quot;%Y&quot;, date.breaks = 4)</code></pre>
<pre><code>## [1] &quot;Taking bootstrap samples. Please wait.&quot;</code></pre>
<div class="figure"><span id="fig:theilSenNO2"></span>
<img src="sccAirQualExplore_covidLockdown2020_files/figure-html/theilSenNO2-1.png" alt="Theil-Sen de-seasoned trend (NO2)" width="672" />
<p class="caption">
Figure 4.1: Theil-Sen de-seasoned trend (NO2)
</p>
</div>
<pre class="r"><code>p &lt;- oaNO2$plot

getModelTrendTable &lt;- function(oa, fname) {
    # oa is an openAir object created by theilSen calculates the % below trend using the theil sen slope line
    # parameters oa &lt;- oaGWh
    oaData &lt;- as.data.table(oa$data$main.data)
    rDT &lt;- oaData[, .(date, conc, a, b, slope)]
    # https://github.com/davidcarslaw/openair/blob/master/R/TheilSen.R#L192 and
    # https://github.com/davidcarslaw/openair/blob/master/R/TheilSen.R#L625
    rDT[, `:=`(x, time_length(date - as.Date(&quot;1970-01-01&quot;), unit = &quot;days&quot;))]  # n days since x = 0
    rDT[, `:=`(expectedVal, a + (b * x))]  # b = slope / 365
    
    # checks
    p &lt;- ggplot2::ggplot(rDT, aes(x = date)) + geom_line(aes(y = conc)) + labs(y = &quot;Value&quot;, caption = fname)
    p &lt;- p + geom_line(aes(y = expectedVal), linetype = &quot;dashed&quot;)
    ggplot2::ggsave(here::here(&quot;docs&quot;, &quot;plots&quot;, paste0(&quot;SSC_trendModelTestPlot_&quot;, fname, &quot;.png&quot;)))
    rDT[, `:=`(diff, conc - expectedVal)]
    rDT[, `:=`(pcDiff, (diff/expectedVal) * 100)]
    
    t &lt;- rDT[, .(date, conc, a, b, slope, expectedVal, diff, pcDiff)]
    return(t)
}

t &lt;- getModelTrendTable(oaNO2, fname = &quot;NO2&quot;)

ft &lt;- dcast(t[date &gt;= as.Date(&quot;2020-01-01&quot;) &amp; date &lt; as.Date(&quot;2020-06-01&quot;)], date ~ ., value.var = c(&quot;diff&quot;, &quot;pcDiff&quot;))
ft[, `:=`(date, format.Date(date, format = &quot;%b %Y&quot;))]
kableExtra::kable(ft, caption = &quot;Units and % above/below expected&quot;, digits = 2) %&gt;% kable_styling()</code></pre>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:theilSenNO2">Table 4.1: </span>Units and % above/below expected
</caption>
<thead>
<tr>
<th style="text-align:left;">
date
</th>
<th style="text-align:right;">
diff
</th>
<th style="text-align:right;">
pcDiff
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Jan 2020
</td>
<td style="text-align:right;">
-3.93
</td>
<td style="text-align:right;">
-12.91
</td>
</tr>
<tr>
<td style="text-align:left;">
Feb 2020
</td>
<td style="text-align:right;">
-4.13
</td>
<td style="text-align:right;">
-13.70
</td>
</tr>
<tr>
<td style="text-align:left;">
Mar 2020
</td>
<td style="text-align:right;">
-6.11
</td>
<td style="text-align:right;">
-20.49
</td>
</tr>
<tr>
<td style="text-align:left;">
Apr 2020
</td>
<td style="text-align:right;">
-3.17
</td>
<td style="text-align:right;">
-10.75
</td>
</tr>
<tr>
<td style="text-align:left;">
May 2020
</td>
<td style="text-align:right;">
-4.65
</td>
<td style="text-align:right;">
-15.94
</td>
</tr>
</tbody>
</table>
<p>Figure <a href="#fig:no2recent">4.2</a> shows the most recent hourly data.</p>
<pre class="r"><code>recentDT &lt;- no2dt[obsDate &gt; myParams$recentCutDate]
p &lt;- makeDotPlot(recentDT, xVar = &quot;dateTimeUTC&quot;, xLab = &quot;Date &amp; Time&quot;, yVar = &quot;value&quot;, byVar = &quot;site&quot;, yLab = yLab)

p &lt;- p + scale_x_datetime(date_breaks = &quot;2 day&quot;, date_labels = &quot;%a %d %b&quot;) + theme(axis.text.x = element_text(angle = 90, 
    hjust = 1))

p &lt;- p + geom_hline(yintercept = myParams$hourlyNo2Threshold_WHO) + labs(caption = paste0(myParams$lockdownCap, 
    myParams$weekendCap, &quot;\nReference line = WHO hourly threshold (&quot;, myParams$hourlyNo2Threshold_WHO, &quot;)&quot;))

# final plot - adds annotations
yMin &lt;- min(recentDT$value)
yMax &lt;- max(recentDT$value)

p &lt;- addLockdownRectDateTime(p, yMin, yMax)
addWeekendsDateTime(p, yMin, yMax) + guides(colour = guide_legend(ncol = 2))</code></pre>
<div class="figure"><span id="fig:no2recent"></span>
<img src="sccAirQualExplore_covidLockdown2020_files/figure-html/no2recent-1.png" alt="Nitrogen Dioxide levels, Southampton (hourly, recent)" width="672" />
<p class="caption">
Figure 4.2: Nitrogen Dioxide levels, Southampton (hourly, recent)
</p>
</div>
<p>Figure <a href="#fig:no2recentProfile">4.3</a> shows the most recent hourly data by date and time of day.</p>
<pre class="r"><code>recentDT[, `:=`(time, hms::as_hms(dateTimeUTC))]
yMin &lt;- min(recentDT$time)
yMax &lt;- max(recentDT$time)
p &lt;- profileTilePlot(recentDT, yLab)
p &lt;- addLockdownRectDate(p, yMin, yMax)
addWeekendsDate(p, yMin, yMax) + labs(caption = paste0(myParams$lockdownCap, myParams$weekendCap))</code></pre>
<div class="figure"><span id="fig:no2recentProfile"></span>
<img src="sccAirQualExplore_covidLockdown2020_files/figure-html/no2recentProfile-1.png" alt="Nitrogen Dioxide levels, Southampton (hourly, recent)" width="672" />
<p class="caption">
Figure 4.3: Nitrogen Dioxide levels, Southampton (hourly, recent)
</p>
</div>
<p>Figure <a href="#fig:no2compare">4.4</a> shows the most recent mean daily values compared to previous years for the two AURN sites which do not have missing data. We have shifted the dates for the comparison years to ensure that weekdays and weekends line up. Note that this plot shows daily means with no indications of variance. Visible differences are therefore purely indicative at this stage.</p>
<pre class="r"><code>plotDT &lt;- no2dt[site %like% &quot;via AURN&quot; &amp; fixedDate &lt;= lubridate::today() &amp; fixedDate &gt;= myParams$comparePlotCut, 
    .(meanVal = mean(value), medianVal = median(value), nSites = uniqueN(site)), keyby = .(fixedDate, compareYear, 
        site)]

# final plot - adds annotations
yMin &lt;- min(plotDT$meanVal)
yMax &lt;- max(plotDT$meanVal)

p &lt;- compareYearsPlot(plotDT, xVar = &quot;fixedDate&quot;, yVar = &quot;meanVal&quot;, colVar = &quot;compareYear&quot;)

p &lt;- addLockdownRectDate(p, yMin, yMax) + labs(x = &quot;Date&quot;, y = &quot;Daily mean&quot;, caption = paste0(myParams$lockdownCap, 
    myParams$weekendCap, myParams$noThresh))

p &lt;- addWeekendsDate(p, yMin, yMax) + scale_x_date(date_breaks = &quot;7 day&quot;, date_labels = &quot;%a %d %b&quot;, date_minor_breaks = &quot;1 day&quot;)

p + facet_grid(site ~ .) + theme(strip.text.y.right = element_text(angle = 90))</code></pre>
<div class="figure"><span id="fig:no2compare"></span>
<img src="sccAirQualExplore_covidLockdown2020_files/figure-html/no2compare-1.png" alt="Comparative Nitrogen Dioxide levels 2020 vs 2017-2019, Southampton (daily mean)" width="672" />
<p class="caption">
Figure 4.4: Comparative Nitrogen Dioxide levels 2020 vs 2017-2019, Southampton (daily mean)
</p>
</div>
<p>Figure <a href="#fig:no2pcDiffcompareDay">4.5</a> and <a href="#fig:no2pcDiffcompareWeek">4.6</a> show the % difference between the daily means for 2020 vs 2017-2019 (reference period). In both cases we can see that NO2 levels in 2020 were generally <em>already</em> lower than the reference period yet are <em>not</em> consistently lower even during the lockdown period. The affects of covid lockdown are not clear cut...</p>
<pre class="r"><code>dailyDT &lt;- makeDailyComparisonDT(no2dt[site %like% &quot;via AURN&quot; &amp; fixedDate &gt;= myParams$comparePlotCut])

p &lt;- compareYearsDiffPlotDaily(dailyDT) + labs(caption = paste0(myParams$lockdownCap, myParams$weekendCap))

yMin &lt;- min(dailyDT$pcDiffMean)
yMax &lt;- max(dailyDT$pcDiffMean)
print(paste0(&quot;Max drop %:&quot;, round(yMin)))</code></pre>
<pre><code>## [1] &quot;Max drop %:-93&quot;</code></pre>
<pre class="r"><code>print(paste0(&quot;Max increase %:&quot;, round(yMax)))</code></pre>
<pre><code>## [1] &quot;Max increase %:124&quot;</code></pre>
<pre class="r"><code>p &lt;- addLockdownRectDate(p, yMin, yMax)
addWeekendsDate(p, yMin, yMax)</code></pre>
<div class="figure"><span id="fig:no2pcDiffcompareDay"></span>
<img src="sccAirQualExplore_covidLockdown2020_files/figure-html/no2pcDiffcompareDay-1.png" alt="Percentage difference in daily mean Nitrogen Dioxide levels 2020 vs 2017-2019, Southampton" width="672" />
<p class="caption">
Figure 4.5: Percentage difference in daily mean Nitrogen Dioxide levels 2020 vs 2017-2019, Southampton
</p>
</div>
<pre class="r"><code>weeklyDT &lt;- makeWeeklyComparisonDT(no2dt[site %like% &quot;via AURN&quot; &amp; fixedDate &gt;= myParams$comparePlotCut])

p &lt;- compareYearsDiffPlotWeekly(weeklyDT, ldStart = myParams$lockDownStartDate, ldEnd = myParams$lockDownEndDate) + 
    labs(caption = paste0(myParams$lockdownCap))

yMin &lt;- min(weeklyDT$pcDiffMean)
yMax &lt;- max(weeklyDT$pcDiffMean)
print(paste0(&quot;Max drop %:&quot;, round(yMin)))</code></pre>
<pre><code>## [1] &quot;Max drop %:-64&quot;</code></pre>
<pre class="r"><code>print(paste0(&quot;Max increase %:&quot;, round(yMax)))</code></pre>
<pre><code>## [1] &quot;Max increase %:38&quot;</code></pre>
<pre class="r"><code>addLockdownRectWeek(p, yMin, yMax)</code></pre>
<div class="figure"><span id="fig:no2pcDiffcompareWeek"></span>
<img src="sccAirQualExplore_covidLockdown2020_files/figure-html/no2pcDiffcompareWeek-1.png" alt="Percentage difference in weekly mean Nitrogen Dioxide levels 2020 vs 2017-2019, Southampton" width="672" />
<p class="caption">
Figure 4.6: Percentage difference in weekly mean Nitrogen Dioxide levels 2020 vs 2017-2019, Southampton
</p>
</div>
<blockquote>
<p>Beware seasonal trends and meteorological affects</p>
</blockquote>
</div>
<div id="oxides-of-nitrogen-nox" class="section level1">
<h1><span class="header-section-number">5</span> Oxides of Nitrogen (nox)</h1>
<pre class="r"><code>yLab &lt;- &quot;Oxides of Nitrogen (ug/m3)&quot;
noxdt &lt;- fixedDT[pollutant == &quot;nox&quot;]</code></pre>
<p>Figure <a href="#fig:theilSenNOx">5.1</a> shows the NOx trend over time. Is lockdown below trend?</p>
<pre class="r"><code>noxdt[, `:=`(date, as.Date(dateTimeUTC))]  # set date to date for this one

oaNOx &lt;- openair::TheilSen(noxdt[date &lt; as.Date(&quot;2020-06-01&quot;)], &quot;value&quot;, ylab = &quot;NOx&quot;, deseason = TRUE, xlab = &quot;Year&quot;, 
    date.format = &quot;%Y&quot;, date.breaks = 4)</code></pre>
<pre><code>## [1] &quot;Taking bootstrap samples. Please wait.&quot;</code></pre>
<div class="figure"><span id="fig:theilSenNOx"></span>
<img src="sccAirQualExplore_covidLockdown2020_files/figure-html/theilSenNOx-1.png" alt="Theil-Sen de-seasoned trend (NOx)" width="672" />
<p class="caption">
Figure 5.1: Theil-Sen de-seasoned trend (NOx)
</p>
</div>
<pre class="r"><code>p &lt;- oaNOx$plot

t &lt;- getModelTrendTable(oaNOx, fname = &quot;NOx&quot;)

ft &lt;- dcast(t[date &gt;= as.Date(&quot;2020-01-01&quot;) &amp; date &lt; as.Date(&quot;2020-06-01&quot;)], date ~ ., value.var = c(&quot;diff&quot;, &quot;pcDiff&quot;))
ft[, `:=`(date, format.Date(date, format = &quot;%b %Y&quot;))]
kableExtra::kable(ft, caption = &quot;Units and % above/below expected&quot;, digits = 2) %&gt;% kable_styling()</code></pre>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:theilSenNOx">Table 5.1: </span>Units and % above/below expected
</caption>
<thead>
<tr>
<th style="text-align:left;">
date
</th>
<th style="text-align:right;">
diff
</th>
<th style="text-align:right;">
pcDiff
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Jan 2020
</td>
<td style="text-align:right;">
-5.11
</td>
<td style="text-align:right;">
-9.30
</td>
</tr>
<tr>
<td style="text-align:left;">
Feb 2020
</td>
<td style="text-align:right;">
-6.81
</td>
<td style="text-align:right;">
-12.55
</td>
</tr>
<tr>
<td style="text-align:left;">
Mar 2020
</td>
<td style="text-align:right;">
-9.41
</td>
<td style="text-align:right;">
-17.54
</td>
</tr>
<tr>
<td style="text-align:left;">
Apr 2020
</td>
<td style="text-align:right;">
-0.35
</td>
<td style="text-align:right;">
-0.66
</td>
</tr>
<tr>
<td style="text-align:left;">
May 2020
</td>
<td style="text-align:right;">
-5.28
</td>
<td style="text-align:right;">
-10.08
</td>
</tr>
</tbody>
</table>
<p>Figure <a href="#fig:noxrecent">5.2</a> shows the most recent hourly data.</p>
<pre class="r"><code>recentDT &lt;- noxdt[!is.na(value) &amp; obsDate &gt; myParams$recentCutDate]
p &lt;- makeDotPlot(recentDT, xVar = &quot;dateTimeUTC&quot;, xLab = &quot;Date &amp; Time&quot;, yVar = &quot;value&quot;, byVar = &quot;site&quot;, yLab = yLab)

p &lt;- p + scale_x_datetime(date_breaks = &quot;2 day&quot;, date_labels = &quot;%a %d %b&quot;) + theme(axis.text.x = element_text(angle = 90, 
    hjust = 1)) + labs(caption = paste0(myParams$lockdownCap, myParams$weekendCap, myParams$noThresh))

# final plot - adds annotations
yMin &lt;- min(recentDT$value)
yMax &lt;- max(recentDT$value)

p &lt;- addLockdownRectDateTime(p, yMin, yMax)

addWeekendsDateTime(p, yMin, yMax)</code></pre>
<div class="figure"><span id="fig:noxrecent"></span>
<img src="sccAirQualExplore_covidLockdown2020_files/figure-html/noxrecent-1.png" alt="Oxides of nitrogen levels, Southampton (hourly, recent)" width="672" />
<p class="caption">
Figure 5.2: Oxides of nitrogen levels, Southampton (hourly, recent)
</p>
</div>
<p>Figure <a href="#fig:noxrecentProfile">5.3</a> shows the most recent hourly data by date and time of day.</p>
<pre class="r"><code>recentDT[, `:=`(time, hms::as_hms(dateTimeUTC))]
yMin &lt;- min(recentDT$time)
yMax &lt;- max(recentDT$time)
p &lt;- profileTilePlot(recentDT, yLab)
addWeekendsDate(p, yMin, yMax) + labs(caption = paste0(myParams$lockdownCap, myParams$weekendCap))</code></pre>
<div class="figure"><span id="fig:noxrecentProfile"></span>
<img src="sccAirQualExplore_covidLockdown2020_files/figure-html/noxrecentProfile-1.png" alt="Oxides of nitrogen levels, Southampton (hourly, recent)" width="672" />
<p class="caption">
Figure 5.3: Oxides of nitrogen levels, Southampton (hourly, recent)
</p>
</div>
<p>Figure <a href="#fig:noxcompare">5.4</a> shows the most recent mean daily values compared to previous years for the two AURN sites.</p>
<pre class="r"><code>plotDT &lt;- noxdt[site %like% &quot;via AURN&quot; &amp; fixedDate &lt;= lubridate::today() &amp; fixedDate &gt;= myParams$comparePlotCut, 
    .(meanVal = mean(value), medianVal = median(value), nSites = uniqueN(site)), keyby = .(fixedDate, compareYear, 
        site)]

# final plot - adds annotations
yMin &lt;- min(plotDT$meanVal)
yMax &lt;- max(plotDT$meanVal)

p &lt;- compareYearsPlot(plotDT, xVar = &quot;fixedDate&quot;, yVar = &quot;meanVal&quot;, colVar = &quot;compareYear&quot;)
p &lt;- addLockdownRectDate(p, yMin, yMax) + labs(x = &quot;Date&quot;, y = &quot;Daily mean&quot;, caption = paste0(myParams$lockdownCap, 
    myParams$weekendCap, myParams$noThresh))
p &lt;- addWeekendsDate(p, yMin, yMax)

p + facet_grid(site ~ .) + theme(strip.text.y.right = element_text(angle = 90))</code></pre>
<div class="figure"><span id="fig:noxcompare"></span>
<img src="sccAirQualExplore_covidLockdown2020_files/figure-html/noxcompare-1.png" alt="Oxides of nitrogen levels, Southampton (daily mean)" width="672" />
<p class="caption">
Figure 5.4: Oxides of nitrogen levels, Southampton (daily mean)
</p>
</div>
<p>Figure <a href="#fig:noxpcDiffcompareDay">5.5</a> and <a href="#fig:noxpcDiffcompareWeek">5.6</a> show the % difference between the daily and weekly means for 2020 vs 2017-2019 (reference period).</p>
<pre class="r"><code>dailyDT &lt;- makeDailyComparisonDT(noxdt[site %like% &quot;via AURN&quot; &amp; fixedDate &gt;= myParams$comparePlotCut])

p &lt;- compareYearsDiffPlotDaily(dailyDT) + labs(caption = paste0(myParams$lockdownCap, myParams$weekendCap))

yMin &lt;- min(dailyDT$pcDiffMean)
yMax &lt;- max(dailyDT$pcDiffMean)
print(paste0(&quot;Max drop %:&quot;, round(yMin)))</code></pre>
<pre><code>## [1] &quot;Max drop %:-96&quot;</code></pre>
<pre class="r"><code>print(paste0(&quot;Max increase %:&quot;, round(yMax)))</code></pre>
<pre><code>## [1] &quot;Max increase %:172&quot;</code></pre>
<pre class="r"><code>p &lt;- addLockdownRectDate(p, yMin, yMax)
addWeekendsDate(p, yMin, yMax)</code></pre>
<div class="figure"><span id="fig:noxpcDiffcompareDay"></span>
<img src="sccAirQualExplore_covidLockdown2020_files/figure-html/noxpcDiffcompareDay-1.png" alt="% difference in daily mean Oxides of Nitrogen levels 2020 vs 2017-2019, Southampton" width="672" />
<p class="caption">
Figure 5.5: % difference in daily mean Oxides of Nitrogen levels 2020 vs 2017-2019, Southampton
</p>
</div>
<pre class="r"><code>weeklyDT &lt;- makeWeeklyComparisonDT(noxdt[site %like% &quot;via AURN&quot; &amp; fixedDate &gt;= myParams$comparePlotCut])

p &lt;- compareYearsDiffPlotWeekly(weeklyDT, ldStart = myParams$lockDownStartDate, ldEnd = myParams$lockDownEndDate) + 
    labs(caption = paste0(myParams$lockdownCap, myParams$weekendCap))

yMin &lt;- min(weeklyDT$pcDiffMean)
yMax &lt;- max(weeklyDT$pcDiffMean)
print(paste0(&quot;Max drop %:&quot;, round(yMin)))</code></pre>
<pre><code>## [1] &quot;Max drop %:-70&quot;</code></pre>
<pre class="r"><code>print(paste0(&quot;Max increase %:&quot;, round(yMax)))</code></pre>
<pre><code>## [1] &quot;Max increase %:51&quot;</code></pre>
<pre class="r"><code>addLockdownRectWeek(p, yMin, yMax)</code></pre>
<div class="figure"><span id="fig:noxpcDiffcompareWeek"></span>
<img src="sccAirQualExplore_covidLockdown2020_files/figure-html/noxpcDiffcompareWeek-1.png" alt="% difference in weekly mean Oxides of Nitrogen levels 2020 vs 2017-2019, Southampton" width="672" />
<p class="caption">
Figure 5.6: % difference in weekly mean Oxides of Nitrogen levels 2020 vs 2017-2019, Southampton
</p>
</div>
</div>
<div id="sulphour-dioxide" class="section level1">
<h1><span class="header-section-number">6</span> Sulphour Dioxide</h1>
<pre class="r"><code>yLab &lt;- &quot;Sulphour Dioxide (ug/m3)&quot;
so2dt &lt;- fixedDT[pollutant == &quot;so2&quot;]</code></pre>
<p>Figure <a href="#fig:theilSenSO2">6.1</a> shows the SO2 trend over time. Is lockdown below trend?</p>
<pre class="r"><code>so2dt[, `:=`(date, as.Date(dateTimeUTC))]  # set date to date for this one

oaSO2 &lt;- openair::TheilSen(so2dt[date &lt; as.Date(&quot;2020-06-01&quot;)], &quot;value&quot;, ylab = &quot;SO2&quot;, deseason = TRUE, xlab = &quot;Year&quot;, 
    date.format = &quot;%Y&quot;, date.breaks = 4)</code></pre>
<pre><code>## [1] &quot;Taking bootstrap samples. Please wait.&quot;</code></pre>
<div class="figure"><span id="fig:theilSenSO2"></span>
<img src="sccAirQualExplore_covidLockdown2020_files/figure-html/theilSenSO2-1.png" alt="Theil-Sen de-seasoned trend (SO2)" width="672" />
<p class="caption">
Figure 6.1: Theil-Sen de-seasoned trend (SO2)
</p>
</div>
<pre class="r"><code>t &lt;- getModelTrendTable(oaSO2, fname = &quot;SO2&quot;)

ft &lt;- dcast(t[date &gt;= as.Date(&quot;2020-01-01&quot;) &amp; date &lt; as.Date(&quot;2020-06-01&quot;)], date ~ ., value.var = c(&quot;diff&quot;, &quot;pcDiff&quot;))
ft[, `:=`(date, format.Date(date, format = &quot;%b %Y&quot;))]
kableExtra::kable(ft, caption = &quot;Units and % above/below expected&quot;, digits = 2) %&gt;% kable_styling()</code></pre>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:theilSenSO2">Table 6.1: </span>Units and % above/below expected
</caption>
<thead>
<tr>
<th style="text-align:left;">
date
</th>
<th style="text-align:right;">
diff
</th>
<th style="text-align:right;">
pcDiff
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Jan 2020
</td>
<td style="text-align:right;">
-0.74
</td>
<td style="text-align:right;">
-41.70
</td>
</tr>
<tr>
<td style="text-align:left;">
Feb 2020
</td>
<td style="text-align:right;">
-0.46
</td>
<td style="text-align:right;">
-25.66
</td>
</tr>
<tr>
<td style="text-align:left;">
Mar 2020
</td>
<td style="text-align:right;">
-0.21
</td>
<td style="text-align:right;">
-11.60
</td>
</tr>
<tr>
<td style="text-align:left;">
Apr 2020
</td>
<td style="text-align:right;">
1.90
</td>
<td style="text-align:right;">
105.20
</td>
</tr>
<tr>
<td style="text-align:left;">
May 2020
</td>
<td style="text-align:right;">
1.21
</td>
<td style="text-align:right;">
66.56
</td>
</tr>
</tbody>
</table>
<p>Figure <a href="#fig:so2recent">6.2</a> shows the most recent hourly data.</p>
<pre class="r"><code>recentDT &lt;- so2dt[!is.na(value) &amp; obsDate &gt; myParams$recentCutDate]
p &lt;- makeDotPlot(recentDT, xVar = &quot;dateTimeUTC&quot;, xLab = &quot;Date &amp; Time&quot;, yVar = &quot;value&quot;, byVar = &quot;site&quot;, yLab = yLab)

p &lt;- p + scale_x_datetime(date_breaks = &quot;2 day&quot;, date_labels = &quot;%a %d %b&quot;) + theme(axis.text.x = element_text(angle = 90, 
    hjust = 1)) + labs(caption = paste0(myParams$lockdownCap, myParams$weekendCap, myParams$noThresh))

yMax &lt;- max(recentDT$value)
yMin &lt;- min(recentDT$value)
p &lt;- addLockdownRectDateTime(p, yMin, yMax)
addWeekendsDateTime(p, yMin, yMax)</code></pre>
<div class="figure"><span id="fig:so2recent"></span>
<img src="sccAirQualExplore_covidLockdown2020_files/figure-html/so2recent-1.png" alt="Sulphour Dioxide levels, Southampton (hourly, recent)" width="672" />
<p class="caption">
Figure 6.2: Sulphour Dioxide levels, Southampton (hourly, recent)
</p>
</div>
<p>Figure <a href="#fig:so2recentProfile">6.3</a> shows the most recent hourly data by date and time of day and time of day.</p>
<pre class="r"><code>recentDT[, `:=`(time, hms::as_hms(dateTimeUTC))]

yMin &lt;- min(recentDT$time)
yMax &lt;- max(recentDT$time)
p &lt;- profileTilePlot(recentDT, yLab)
addWeekendsDate(p, yMin, yMax) + labs(caption = paste0(myParams$lockdownCap, myParams$weekendCap))</code></pre>
<div class="figure"><span id="fig:so2recentProfile"></span>
<img src="sccAirQualExplore_covidLockdown2020_files/figure-html/so2recentProfile-1.png" alt="Sulphour Dioxide levels, Southampton (hourly, recent)" width="672" />
<p class="caption">
Figure 6.3: Sulphour Dioxide levels, Southampton (hourly, recent)
</p>
</div>
<p>Figure <a href="#fig:so2compare">6.4</a> shows the most recent mean daily values compared to previous years.</p>
<pre class="r"><code>plotDT &lt;- so2dt[site %like% &quot;via AURN&quot; &amp; fixedDate &lt;= lubridate::today() &amp; fixedDate &gt;= myParams$comparePlotCut, 
    .(meanVal = mean(value), medianVal = median(value), nSites = uniqueN(site)), keyby = .(fixedDate, compareYear, 
        site)]

# final plot - adds annotations
yMin &lt;- min(plotDT$mean)
yMax &lt;- max(plotDT$mean)

p &lt;- compareYearsPlot(plotDT, xVar = &quot;fixedDate&quot;, yVar = &quot;meanVal&quot;, colVar = &quot;compareYear&quot;)
p &lt;- addLockdownRectDate(p, yMin, yMax) + geom_hline(yintercept = myParams$dailySo2Threshold_WHO) + labs(x = &quot;Date&quot;, 
    y = &quot;Daily mean&quot;, caption = paste0(myParams$lockdownCap, myParams$weekendCap, &quot;\nReference line = WHO daily threshold (&quot;, 
        myParams$dailySo2Threshold_WHO, &quot;)&quot;))
p &lt;- addWeekendsDate(p, yMin, yMax)

p + facet_grid(site ~ .) + theme(strip.text.y.right = element_text(angle = 90))</code></pre>
<div class="figure"><span id="fig:so2compare"></span>
<img src="sccAirQualExplore_covidLockdown2020_files/figure-html/so2compare-1.png" alt="Sulphour dioxide levels, Southampton (daily mean)" width="672" />
<p class="caption">
Figure 6.4: Sulphour dioxide levels, Southampton (daily mean)
</p>
</div>
<p>Figure <a href="#fig:so2pcDiffcompareDay">6.5</a> and <a href="#fig:so2pcDiffcompareWeek">6.6</a> show the % difference between the daily and weekly means for 2020 vs 2017-2019 (reference period).</p>
<pre class="r"><code>dailyDT &lt;- makeDailyComparisonDT(so2dt[site %like% &quot;via AURN&quot; &amp; fixedDate &gt;= myParams$comparePlotCut])

p &lt;- compareYearsDiffPlotDaily(dailyDT) + labs(caption = paste0(myParams$lockdownCap))

yMin &lt;- min(dailyDT$pcDiffMean)
yMax &lt;- max(dailyDT$pcDiffMean)
print(paste0(&quot;Max drop %:&quot;, round(yMin)))</code></pre>
<pre><code>## [1] &quot;Max drop %:-75&quot;</code></pre>
<pre class="r"><code>print(paste0(&quot;Max increase %:&quot;, round(yMax)))</code></pre>
<pre><code>## [1] &quot;Max increase %:714&quot;</code></pre>
<pre class="r"><code>p &lt;- addLockdownRectDate(p, yMin, yMax)
addWeekendsDate(p, yMin, yMax)</code></pre>
<div class="figure"><span id="fig:so2pcDiffcompareDay"></span>
<img src="sccAirQualExplore_covidLockdown2020_files/figure-html/so2pcDiffcompareDay-1.png" alt="% difference in daily mean Sulphour Dioxide levels 2020 vs 2017-2019, Southampton" width="672" />
<p class="caption">
Figure 6.5: % difference in daily mean Sulphour Dioxide levels 2020 vs 2017-2019, Southampton
</p>
</div>
<pre class="r"><code>weeklyDT &lt;- makeWeeklyComparisonDT(so2dt[site %like% &quot;via AURN&quot; &amp; fixedDate &gt;= myParams$comparePlotCut])

p &lt;- compareYearsDiffPlotWeekly(weeklyDT, ldStart = myParams$lockDownStartDate, ldEnd = myParams$lockDownEndDate) + 
    labs(caption = paste0(myParams$lockdownCap))

yMin &lt;- min(weeklyDT$pcDiffMean)
yMax &lt;- max(weeklyDT$pcDiffMean)
print(paste0(&quot;Max drop %:&quot;, round(yMin)))</code></pre>
<pre><code>## [1] &quot;Max drop %:-48&quot;</code></pre>
<pre class="r"><code>print(paste0(&quot;Max increase %:&quot;, round(yMax)))</code></pre>
<pre><code>## [1] &quot;Max increase %:415&quot;</code></pre>
<pre class="r"><code>addLockdownRectWeek(p, yMin, yMax)</code></pre>
<div class="figure"><span id="fig:so2pcDiffcompareWeek"></span>
<img src="sccAirQualExplore_covidLockdown2020_files/figure-html/so2pcDiffcompareWeek-1.png" alt="% difference in weekly mean Sulphour Dioxide levels 2020 vs 2017-2019, Southampton" width="672" />
<p class="caption">
Figure 6.6: % difference in weekly mean Sulphour Dioxide levels 2020 vs 2017-2019, Southampton
</p>
</div>
<blockquote>
<p>Beware seasonal trends and meteorological affects</p>
</blockquote>
</div>
<div id="ozone" class="section level1">
<h1><span class="header-section-number">7</span> Ozone</h1>
<pre class="r"><code>yLab &lt;- &quot;Ozone (ug/m3)&quot;
o3dt &lt;- fixedDT[pollutant == &quot;o3&quot;]</code></pre>
<p>Figure <a href="#fig:theilSenO3">7.1</a> shows the O3 trend over time. Is lockdown below trend?</p>
<pre class="r"><code>o3dt[, `:=`(date, as.Date(dateTimeUTC))]  # set date to date for this one

oaO3 &lt;- openair::TheilSen(o3dt[date &lt; as.Date(&quot;2020-06-01&quot;)], &quot;value&quot;, ylab = &quot;O3&quot;, deseason = TRUE, xlab = &quot;Year&quot;, 
    date.format = &quot;%Y&quot;, date.breaks = 4)</code></pre>
<pre><code>## [1] &quot;Taking bootstrap samples. Please wait.&quot;</code></pre>
<div class="figure"><span id="fig:theilSenO3"></span>
<img src="sccAirQualExplore_covidLockdown2020_files/figure-html/theilSenO3-1.png" alt="Theil-Sen de-seasoned trend (O3)" width="672" />
<p class="caption">
Figure 7.1: Theil-Sen de-seasoned trend (O3)
</p>
</div>
<pre class="r"><code>t &lt;- getModelTrendTable(oaO3, fname = &quot;O3&quot;)

ft &lt;- dcast(t[date &gt;= as.Date(&quot;2020-01-01&quot;) &amp; date &lt; as.Date(&quot;2020-06-01&quot;)], date ~ ., value.var = c(&quot;diff&quot;, &quot;pcDiff&quot;))
ft[, `:=`(date, format.Date(date, format = &quot;%b %Y&quot;))]
kableExtra::kable(ft, caption = &quot;Units and % above/below expected&quot;, digits = 2) %&gt;% kable_styling()</code></pre>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:theilSenO3">Table 7.1: </span>Units and % above/below expected
</caption>
<thead>
<tr>
<th style="text-align:left;">
date
</th>
<th style="text-align:right;">
diff
</th>
<th style="text-align:right;">
pcDiff
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Jan 2020
</td>
<td style="text-align:right;">
4.30
</td>
<td style="text-align:right;">
9.31
</td>
</tr>
<tr>
<td style="text-align:left;">
Feb 2020
</td>
<td style="text-align:right;">
8.84
</td>
<td style="text-align:right;">
19.07
</td>
</tr>
<tr>
<td style="text-align:left;">
Mar 2020
</td>
<td style="text-align:right;">
4.77
</td>
<td style="text-align:right;">
10.25
</td>
</tr>
<tr>
<td style="text-align:left;">
Apr 2020
</td>
<td style="text-align:right;">
4.31
</td>
<td style="text-align:right;">
9.22
</td>
</tr>
<tr>
<td style="text-align:left;">
May 2020
</td>
<td style="text-align:right;">
6.80
</td>
<td style="text-align:right;">
14.48
</td>
</tr>
</tbody>
</table>
<p>Figure <a href="#fig:03recent">7.2</a> shows the most recent hourly data.</p>
<pre class="r"><code>recentDT &lt;- o3dt[!is.na(value) &amp; obsDate &gt; myParams$recentCutDate]
p &lt;- makeDotPlot(recentDT, xVar = &quot;dateTimeUTC&quot;, xLab = &quot;Date &amp; Time&quot;, yVar = &quot;value&quot;, byVar = &quot;site&quot;, yLab = yLab)

p &lt;- p + scale_x_datetime(date_breaks = &quot;2 day&quot;, date_labels = &quot;%a %d %b&quot;) + theme(axis.text.x = element_text(angle = 90, 
    hjust = 1)) + labs(caption = paste0(myParams$lockdownCap, myParams$weekendCap, myParams$noThresh))

yMax &lt;- max(recentDT$value)
yMin &lt;- min(recentDT$value)
p &lt;- addLockdownRectDateTime(p, yMin, yMax)
addWeekendsDateTime(p, yMin, yMax)</code></pre>
<div class="figure"><span id="fig:03recent"></span>
<img src="sccAirQualExplore_covidLockdown2020_files/figure-html/03recent-1.png" alt="03 levels, Southampton (hourly, recent)" width="672" />
<p class="caption">
Figure 7.2: 03 levels, Southampton (hourly, recent)
</p>
</div>
<p>Figure <a href="#fig:o3recentProfile">7.3</a> shows the most recent hourly data by date and time of day.</p>
<pre class="r"><code>recentDT[, `:=`(time, hms::as_hms(dateTimeUTC))]

yMin &lt;- min(recentDT$time)
yMax &lt;- max(recentDT$time)
p &lt;- profileTilePlot(recentDT, yLab)
addWeekendsDate(p, yMin, yMax) + labs(caption = paste0(myParams$lockdownCap, myParams$weekendCap))</code></pre>
<div class="figure"><span id="fig:o3recentProfile"></span>
<img src="sccAirQualExplore_covidLockdown2020_files/figure-html/o3recentProfile-1.png" alt="Ozone levels, Southampton (hourly, recent)" width="672" />
<p class="caption">
Figure 7.3: Ozone levels, Southampton (hourly, recent)
</p>
</div>
<p>Figure <a href="#fig:o3compare">7.4</a> shows the most recent mean daily values compared to previous years.</p>
<pre class="r"><code>plotDT &lt;- o3dt[site %like% &quot;via AURN&quot; &amp; fixedDate &lt;= lubridate::today() &amp; fixedDate &gt;= myParams$comparePlotCut, 
    .(meanVal = mean(value), medianVal = median(value), nSites = uniqueN(site)), keyby = .(fixedDate, compareYear, 
        site)]

# final plot - adds annotations
yMin &lt;- min(plotDT$mean)
yMax &lt;- max(plotDT$mean)

p &lt;- compareYearsPlot(plotDT, xVar = &quot;fixedDate&quot;, yVar = &quot;meanVal&quot;, colVar = &quot;compareYear&quot;)
p &lt;- addLockdownRectDate(p, yMin, yMax) + geom_hline(yintercept = myParams$dailyO3Threshold_WHO) + labs(x = &quot;Date&quot;, 
    y = &quot;Daily mean&quot;, caption = paste0(myParams$lockdownCap, myParams$weekendCap, &quot;\nReference line = WHO daily threshold (&quot;, 
        myParams$dailyO3Threshold_WHO, &quot;)&quot;))
p &lt;- addWeekendsDate(p, yMin, yMax)
p + facet_grid(site ~ .) + theme(strip.text.y.right = element_text(angle = 90))</code></pre>
<div class="figure"><span id="fig:o3compare"></span>
<img src="sccAirQualExplore_covidLockdown2020_files/figure-html/o3compare-1.png" alt="Ozone levels, Southampton (daily mean)" width="672" />
<p class="caption">
Figure 7.4: Ozone levels, Southampton (daily mean)
</p>
</div>
<p>Figure <a href="#fig:o3pcDiffcompareDay">7.5</a> and <a href="#fig:o3pcDiffcompareWeek">7.6</a> show the % difference between the daily and weekly means for 2020 vs 2017-2019 (reference period).</p>
<pre class="r"><code>dailyDT &lt;- makeDailyComparisonDT(o3dt[site %like% &quot;via AURN&quot; &amp; fixedDate &gt;= myParams$comparePlotCut])

p &lt;- compareYearsDiffPlotDaily(dailyDT) + labs(caption = paste0(myParams$lockdownCap))

yMin &lt;- min(dailyDT$pcDiffMean)
yMax &lt;- max(dailyDT$pcDiffMean)
print(paste0(&quot;Max drop %:&quot;, round(yMin)))</code></pre>
<pre><code>## [1] &quot;Max drop %:-53&quot;</code></pre>
<pre class="r"><code>print(paste0(&quot;Max increase %:&quot;, round(yMax)))</code></pre>
<pre><code>## [1] &quot;Max increase %:121&quot;</code></pre>
<pre class="r"><code>p &lt;- addLockdownRectDate(p, yMin, yMax)
addWeekendsDate(p, yMin, yMax)</code></pre>
<div class="figure"><span id="fig:o3pcDiffcompareDay"></span>
<img src="sccAirQualExplore_covidLockdown2020_files/figure-html/o3pcDiffcompareDay-1.png" alt="% difference in daily mean Ozone levels 2020 vs 2017-2019, Southampton" width="672" />
<p class="caption">
Figure 7.5: % difference in daily mean Ozone levels 2020 vs 2017-2019, Southampton
</p>
</div>
<pre class="r"><code>weeklyDT &lt;- makeWeeklyComparisonDT(o3dt[site %like% &quot;via AURN&quot; &amp; fixedDate &gt;= myParams$comparePlotCut])

p &lt;- compareYearsDiffPlotWeekly(weeklyDT, ldStart = myParams$lockDownStartDate, ldEnd = myParams$lockDownEndDate) + 
    labs(caption = paste0(myParams$lockdownCap))

yMin &lt;- min(weeklyDT$pcDiffMean)
yMax &lt;- max(weeklyDT$pcDiffMean)
print(paste0(&quot;Max drop %:&quot;, round(yMin)))</code></pre>
<pre><code>## [1] &quot;Max drop %:1&quot;</code></pre>
<pre class="r"><code>print(paste0(&quot;Max increase %:&quot;, round(yMax)))</code></pre>
<pre><code>## [1] &quot;Max increase %:87&quot;</code></pre>
<pre class="r"><code>addLockdownRectWeek(p, yMin, yMax)</code></pre>
<div class="figure"><span id="fig:o3pcDiffcompareWeek"></span>
<img src="sccAirQualExplore_covidLockdown2020_files/figure-html/o3pcDiffcompareWeek-1.png" alt="% difference in weekly mean Ozone levels 2020 vs 2017-2019, Southampton" width="672" />
<p class="caption">
Figure 7.6: % difference in weekly mean Ozone levels 2020 vs 2017-2019, Southampton
</p>
</div>
<blockquote>
<p>Beware seasonal trends and meteorological affects</p>
</blockquote>
</div>
<div id="pm-10" class="section level1">
<h1><span class="header-section-number">8</span> PM 10</h1>
<pre class="r"><code>yLab &lt;- &quot;PM 10 (ug/m3)&quot;
pm10dt &lt;- fixedDT[pollutant == &quot;pm10&quot;]</code></pre>
<p>Figure <a href="#fig:theilSenPM10">8.1</a> shows the PM10 trend over time. Is lockdown below trend?</p>
<pre class="r"><code>pm10dt[, `:=`(date, as.Date(dateTimeUTC))]  # set date to date for this one

oaPM10 &lt;- openair::TheilSen(pm10dt[date &lt; as.Date(&quot;2020-06-01&quot;)], &quot;value&quot;, ylab = &quot;PM10&quot;, deseason = TRUE, xlab = &quot;Year&quot;, 
    date.format = &quot;%Y&quot;, date.breaks = 4)</code></pre>
<pre><code>## [1] &quot;Taking bootstrap samples. Please wait.&quot;</code></pre>
<div class="figure"><span id="fig:theilSenPM10"></span>
<img src="sccAirQualExplore_covidLockdown2020_files/figure-html/theilSenPM10-1.png" alt="Theil-Sen de-seasoned trend (PM10)" width="672" />
<p class="caption">
Figure 8.1: Theil-Sen de-seasoned trend (PM10)
</p>
</div>
<pre class="r"><code>t &lt;- getModelTrendTable(oaPM10, fname = &quot;SPM10&quot;)

ft &lt;- dcast(t[date &gt;= as.Date(&quot;2020-01-01&quot;) &amp; date &lt; as.Date(&quot;2020-06-01&quot;)], date ~ ., value.var = c(&quot;diff&quot;, &quot;pcDiff&quot;))
ft[, `:=`(date, format.Date(date, format = &quot;%b %Y&quot;))]
kableExtra::kable(ft, caption = &quot;Units and % above/below expected&quot;, digits = 2) %&gt;% kable_styling()</code></pre>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:theilSenPM10">Table 8.1: </span>Units and % above/below expected
</caption>
<thead>
<tr>
<th style="text-align:left;">
date
</th>
<th style="text-align:right;">
diff
</th>
<th style="text-align:right;">
pcDiff
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Jan 2020
</td>
<td style="text-align:right;">
-0.10
</td>
<td style="text-align:right;">
-0.62
</td>
</tr>
<tr>
<td style="text-align:left;">
Feb 2020
</td>
<td style="text-align:right;">
-1.58
</td>
<td style="text-align:right;">
-10.10
</td>
</tr>
<tr>
<td style="text-align:left;">
Mar 2020
</td>
<td style="text-align:right;">
1.55
</td>
<td style="text-align:right;">
9.91
</td>
</tr>
<tr>
<td style="text-align:left;">
Apr 2020
</td>
<td style="text-align:right;">
-0.06
</td>
<td style="text-align:right;">
-0.38
</td>
</tr>
<tr>
<td style="text-align:left;">
May 2020
</td>
<td style="text-align:right;">
1.57
</td>
<td style="text-align:right;">
10.19
</td>
</tr>
</tbody>
</table>
<p>Figure <a href="#fig:pm10recent">8.2</a> shows the most recent hourly data.</p>
<pre class="r"><code>recentDT &lt;- pm10dt[!is.na(value) &amp; obsDate &gt; myParams$recentCutDate]
p &lt;- makeDotPlot(recentDT, xVar = &quot;dateTimeUTC&quot;, xLab = &quot;Date &amp; Time&quot;, yVar = &quot;value&quot;, byVar = &quot;site&quot;, yLab = yLab)

p &lt;- p + scale_x_datetime(date_breaks = &quot;2 day&quot;, date_labels = &quot;%a %d %b&quot;) + theme(axis.text.x = element_text(angle = 90, 
    hjust = 1)) + labs(caption = paste0(myParams$lockdownCap, myParams$weekendCap, myParams$noThresh))

yMax &lt;- max(recentDT$value)
yMin &lt;- min(recentDT$value)
p &lt;- addLockdownRectDateTime(p, yMin, yMax)
addWeekendsDateTime(p, yMin, yMax)</code></pre>
<div class="figure"><span id="fig:pm10recent"></span>
<img src="sccAirQualExplore_covidLockdown2020_files/figure-html/pm10recent-1.png" alt="PM10 levels, Southampton (hourly, recent)" width="672" />
<p class="caption">
Figure 8.2: PM10 levels, Southampton (hourly, recent)
</p>
</div>
<p>Figure <a href="#fig:pm10recentProfile">8.3</a> shows the most recent hourly data by date and time of day.</p>
<pre class="r"><code>recentDT[, `:=`(time, hms::as_hms(dateTimeUTC))]

yMin &lt;- min(recentDT$time)
yMax &lt;- max(recentDT$time)
p &lt;- profileTilePlot(recentDT, yLab)
addWeekendsDate(p, yMin, yMax) + labs(caption = paste0(myParams$lockdownCap, myParams$weekendCap))</code></pre>
<div class="figure"><span id="fig:pm10recentProfile"></span>
<img src="sccAirQualExplore_covidLockdown2020_files/figure-html/pm10recentProfile-1.png" alt="PM10 levels, Southampton (hourly, recent)" width="672" />
<p class="caption">
Figure 8.3: PM10 levels, Southampton (hourly, recent)
</p>
</div>
<p>Figure <a href="#fig:pm10compare">8.4</a> shows the most recent mean daily values compared to previous years.</p>
<pre class="r"><code>plotDT &lt;- pm10dt[site %like% &quot;via AURN&quot; &amp; fixedDate &lt;= lubridate::today() &amp; fixedDate &gt;= myParams$comparePlotCut, 
    .(meanVal = mean(value), medianVal = median(value), nSites = uniqueN(site)), keyby = .(fixedDate, compareYear, 
        site)]

# final plot - adds annotations
yMin &lt;- min(plotDT$mean)
yMax &lt;- max(plotDT$mean)

p &lt;- compareYearsPlot(plotDT, xVar = &quot;fixedDate&quot;, yVar = &quot;meanVal&quot;, colVar = &quot;compareYear&quot;)
p &lt;- addLockdownRectDate(p, yMin, yMax) + geom_hline(yintercept = myParams$dailyPm10Threshold_WHO) + labs(x = &quot;Date&quot;, 
    y = &quot;Daily mean&quot;, caption = paste0(myParams$lockdownCap, myParams$weekendCap, &quot;\nReference line = WHO daily threshold (&quot;, 
        myParams$dailyPm10Threshold_WHO, &quot;)&quot;))
p &lt;- addWeekendsDate(p, yMin, yMax)
p + facet_grid(site ~ .) + theme(strip.text.y.right = element_text(angle = 90))</code></pre>
<div class="figure"><span id="fig:pm10compare"></span>
<img src="sccAirQualExplore_covidLockdown2020_files/figure-html/pm10compare-1.png" alt="PM10 levels, Southampton (daily mean)" width="672" />
<p class="caption">
Figure 8.4: PM10 levels, Southampton (daily mean)
</p>
</div>
<p>Figure <a href="#fig:pm10pcDiffcompareDay">8.5</a> and <a href="#fig:pm10pcDiffcompareWeek">8.6</a> show the % difference between the daily and weekly means for 2020 vs 2017-2019 (reference period).</p>
<pre class="r"><code>dailyDT &lt;- makeDailyComparisonDT(pm10dt[site %like% &quot;via AURN&quot; &amp; fixedDate &gt;= myParams$comparePlotCut])

p &lt;- compareYearsDiffPlotDaily(dailyDT) + labs(caption = paste0(myParams$lockdownCap))

yMin &lt;- min(dailyDT$pcDiffMean)
yMax &lt;- max(dailyDT$pcDiffMean)
print(paste0(&quot;Max drop %:&quot;, round(yMin)))</code></pre>
<pre><code>## [1] &quot;Max drop %:-79&quot;</code></pre>
<pre class="r"><code>print(paste0(&quot;Max increase %:&quot;, round(yMax)))</code></pre>
<pre><code>## [1] &quot;Max increase %:203&quot;</code></pre>
<pre class="r"><code>p &lt;- addLockdownRectDate(p, yMin, yMax)
addWeekendsDate(p, yMin, yMax)</code></pre>
<div class="figure"><span id="fig:pm10pcDiffcompareDay"></span>
<img src="sccAirQualExplore_covidLockdown2020_files/figure-html/pm10pcDiffcompareDay-1.png" alt="% difference in daily mean PM10 levels 2020 vs 2017-2019, Southampton" width="672" />
<p class="caption">
Figure 8.5: % difference in daily mean PM10 levels 2020 vs 2017-2019, Southampton
</p>
</div>
<pre class="r"><code>weeklyDT &lt;- makeWeeklyComparisonDT(pm10dt[site %like% &quot;via AURN&quot; &amp; fixedDate &gt;= myParams$comparePlotCut])

p &lt;- compareYearsDiffPlotWeekly(weeklyDT, ldStart = myParams$lockDownStartDate, ldEnd = myParams$lockDownEndDate) + 
    labs(caption = paste0(myParams$lockdownCap))

yMin &lt;- min(weeklyDT$pcDiffMean)
yMax &lt;- max(weeklyDT$pcDiffMean)
print(paste0(&quot;Max drop %:&quot;, round(yMin)))</code></pre>
<pre><code>## [1] &quot;Max drop %:-46&quot;</code></pre>
<pre class="r"><code>print(paste0(&quot;Max increase %:&quot;, round(yMax)))</code></pre>
<pre><code>## [1] &quot;Max increase %:81&quot;</code></pre>
<pre class="r"><code>addLockdownRectWeek(p, yMin, yMax)</code></pre>
<div class="figure"><span id="fig:pm10pcDiffcompareWeek"></span>
<img src="sccAirQualExplore_covidLockdown2020_files/figure-html/pm10pcDiffcompareWeek-1.png" alt="% difference in weekly mean PM10 levels 2020 vs 2017-2019, Southampton" width="672" />
<p class="caption">
Figure 8.6: % difference in weekly mean PM10 levels 2020 vs 2017-2019, Southampton
</p>
</div>
<blockquote>
<p>Beware seasonal trends and meteorological affects</p>
</blockquote>
</div>
<div id="pm-2.5" class="section level1">
<h1><span class="header-section-number">9</span> PM 2.5</h1>
<pre class="r"><code>yLab &lt;- &quot;PM 2.5 (ug/m3)&quot;
pm25dt &lt;- fixedDT[pollutant == &quot;pm2.5&quot;]</code></pre>
<p>Figure <a href="#fig:theilSenPM25">9.1</a> shows the PM10 trend over time. Is lockdown below trend?</p>
<pre class="r"><code>pm25dt[, `:=`(date, as.Date(dateTimeUTC))]  # set date to date for this one

oaPM25 &lt;- openair::TheilSen(pm25dt[date &lt; as.Date(&quot;2020-06-01&quot;)], &quot;value&quot;, ylab = &quot;PM2.5&quot;, deseason = TRUE, xlab = &quot;Year&quot;, 
    date.format = &quot;%Y&quot;, date.breaks = 4)</code></pre>
<pre><code>## [1] &quot;Taking bootstrap samples. Please wait.&quot;</code></pre>
<div class="figure"><span id="fig:theilSenPM25"></span>
<img src="sccAirQualExplore_covidLockdown2020_files/figure-html/theilSenPM25-1.png" alt="Theil-Sen de-seasoned trend (PM2.5)" width="672" />
<p class="caption">
Figure 9.1: Theil-Sen de-seasoned trend (PM2.5)
</p>
</div>
<pre class="r"><code>t &lt;- getModelTrendTable(oaPM25, fname = &quot;PM2.5&quot;)

ft &lt;- dcast(t[date &gt;= as.Date(&quot;2020-01-01&quot;) &amp; date &lt; as.Date(&quot;2020-06-01&quot;)], date ~ ., value.var = c(&quot;diff&quot;, &quot;pcDiff&quot;))
ft[, `:=`(date, format.Date(date, format = &quot;%b %Y&quot;))]
kableExtra::kable(ft, caption = &quot;Units and % above/below expected&quot;, digits = 2) %&gt;% kable_styling()</code></pre>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:theilSenPM25">Table 9.1: </span>Units and % above/below expected
</caption>
<thead>
<tr>
<th style="text-align:left;">
date
</th>
<th style="text-align:right;">
diff
</th>
<th style="text-align:right;">
pcDiff
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Jan 2020
</td>
<td style="text-align:right;">
0.70
</td>
<td style="text-align:right;">
7.70
</td>
</tr>
<tr>
<td style="text-align:left;">
Feb 2020
</td>
<td style="text-align:right;">
-0.42
</td>
<td style="text-align:right;">
-4.72
</td>
</tr>
<tr>
<td style="text-align:left;">
Mar 2020
</td>
<td style="text-align:right;">
0.38
</td>
<td style="text-align:right;">
4.27
</td>
</tr>
<tr>
<td style="text-align:left;">
Apr 2020
</td>
<td style="text-align:right;">
1.59
</td>
<td style="text-align:right;">
18.11
</td>
</tr>
<tr>
<td style="text-align:left;">
May 2020
</td>
<td style="text-align:right;">
1.73
</td>
<td style="text-align:right;">
19.89
</td>
</tr>
</tbody>
</table>
<p>Figure <a href="#fig:pm25recent">9.2</a> shows the most recent hourly data.</p>
<pre class="r"><code>recentDT &lt;- pm25dt[!is.na(value) &amp; obsDate &gt; myParams$recentCutDate]
p &lt;- makeDotPlot(recentDT, xVar = &quot;dateTimeUTC&quot;, xLab = &quot;Date &amp; Time&quot;, yVar = &quot;value&quot;, byVar = &quot;site&quot;, yLab = yLab)

p &lt;- p + scale_x_datetime(date_breaks = &quot;2 day&quot;, date_labels = &quot;%a %d %b&quot;) + theme(axis.text.x = element_text(angle = 90, 
    hjust = 1)) + labs(caption = paste0(myParams$lockdownCap, myParams$weekendCap, myParams$noThresh))

yMax &lt;- max(recentDT$value)
yMin &lt;- min(recentDT$value)
p &lt;- addLockdownRectDateTime(p, yMin, yMax)
addWeekendsDateTime(p, yMin, yMax)</code></pre>
<div class="figure"><span id="fig:pm25recent"></span>
<img src="sccAirQualExplore_covidLockdown2020_files/figure-html/pm25recent-1.png" alt="PM2.5 levels, Southampton (hourly, recent)" width="672" />
<p class="caption">
Figure 9.2: PM2.5 levels, Southampton (hourly, recent)
</p>
</div>
<p>Figure <a href="#fig:pm25recentProfile">9.3</a> shows the most recent hourly data by date and time of day.</p>
<pre class="r"><code>recentDT[, `:=`(time, hms::as_hms(dateTimeUTC))]

yMin &lt;- min(recentDT$time)
yMax &lt;- max(recentDT$time)
p &lt;- profileTilePlot(recentDT, yLab)
addWeekendsDate(p, yMin, yMax) + labs(caption = paste0(myParams$lockdownCap, myParams$weekendCap))</code></pre>
<div class="figure"><span id="fig:pm25recentProfile"></span>
<img src="sccAirQualExplore_covidLockdown2020_files/figure-html/pm25recentProfile-1.png" alt="PM2.5 levels, Southampton (hourly, recent)" width="672" />
<p class="caption">
Figure 9.3: PM2.5 levels, Southampton (hourly, recent)
</p>
</div>
<p>Figure <a href="#fig:pm25compare">9.4</a> shows the most recent mean daily values compared to previous years.</p>
<pre class="r"><code>plotDT &lt;- pm25dt[site %like% &quot;via AURN&quot; &amp; fixedDate &lt;= lubridate::today() &amp; fixedDate &gt;= myParams$comparePlotCut, 
    .(meanVal = mean(value), medianVal = median(value), nSites = uniqueN(site)), keyby = .(fixedDate, compareYear, 
        site)]

# final plot - adds annotations
yMin &lt;- min(plotDT$mean)
yMax &lt;- max(plotDT$mean)

p &lt;- compareYearsPlot(plotDT, xVar = &quot;fixedDate&quot;, yVar = &quot;meanVal&quot;, colVar = &quot;compareYear&quot;)
p &lt;- addLockdownRectDate(p, yMin, yMax) + geom_hline(yintercept = myParams$dailyPm2.5Threshold_WHO) + labs(x = &quot;Date&quot;, 
    y = &quot;Daily mean&quot;, caption = paste0(myParams$lockdownCap, myParams$weekendCap, &quot;\nReference line = WHO daily threshold (&quot;, 
        myParams$dailyPm2.5Threshold_WHO, &quot;)&quot;))
p &lt;- addWeekendsDate(p, yMin, yMax)
p + facet_grid(site ~ .) + theme(strip.text.y.right = element_text(angle = 90))</code></pre>
<div class="figure"><span id="fig:pm25compare"></span>
<img src="sccAirQualExplore_covidLockdown2020_files/figure-html/pm25compare-1.png" alt="PM2.5 levels, Southampton (daily mean)" width="672" />
<p class="caption">
Figure 9.4: PM2.5 levels, Southampton (daily mean)
</p>
</div>
<p>Figure <a href="#fig:pm25pcDiffcompareDay">9.5</a> and <a href="#fig:pm25pcDiffcompareWeek">9.6</a> show the % difference between the daily and weekly means for 2020 vs 2017-2019 (reference period).</p>
<pre class="r"><code>dailyDT &lt;- makeDailyComparisonDT(pm25dt[site %like% &quot;via AURN&quot; &amp; fixedDate &gt;= myParams$comparePlotCut])

p &lt;- compareYearsDiffPlotDaily(dailyDT) + labs(caption = paste0(myParams$lockdownCap))

yMin &lt;- min(dailyDT$pcDiffMean)
yMax &lt;- max(dailyDT$pcDiffMean)
print(paste0(&quot;Max drop %:&quot;, round(yMin)))</code></pre>
<pre><code>## [1] &quot;Max drop %:-81&quot;</code></pre>
<pre class="r"><code>print(paste0(&quot;Max increase %:&quot;, round(yMax)))</code></pre>
<pre><code>## [1] &quot;Max increase %:263&quot;</code></pre>
<pre class="r"><code>p &lt;- addLockdownRectDate(p, yMin, yMax)
addWeekendsDate(p, yMin, yMax)</code></pre>
<div class="figure"><span id="fig:pm25pcDiffcompareDay"></span>
<img src="sccAirQualExplore_covidLockdown2020_files/figure-html/pm25pcDiffcompareDay-1.png" alt="% difference in daily mean PM2.5 levels 2020 vs 2017-2019, Southampton" width="672" />
<p class="caption">
Figure 9.5: % difference in daily mean PM2.5 levels 2020 vs 2017-2019, Southampton
</p>
</div>
<pre class="r"><code>weeklyDT &lt;- makeWeeklyComparisonDT(pm25dt[site %like% &quot;via AURN&quot; &amp; fixedDate &gt;= myParams$comparePlotCut])

p &lt;- compareYearsDiffPlotWeekly(weeklyDT, ldStart = myParams$lockDownStartDate, ldEnd = myParams$lockDownEndDate) + 
    labs(caption = paste0(myParams$lockdownCap))

yMin &lt;- min(weeklyDT$pcDiffMean)
yMax &lt;- max(weeklyDT$pcDiffMean)
print(paste0(&quot;Max drop %:&quot;, round(yMin)))</code></pre>
<pre><code>## [1] &quot;Max drop %:-54&quot;</code></pre>
<pre class="r"><code>print(paste0(&quot;Max increase %:&quot;, round(yMax)))</code></pre>
<pre><code>## [1] &quot;Max increase %:95&quot;</code></pre>
<pre class="r"><code>addLockdownRectWeek(p, yMin, yMax)</code></pre>
<div class="figure"><span id="fig:pm25pcDiffcompareWeek"></span>
<img src="sccAirQualExplore_covidLockdown2020_files/figure-html/pm25pcDiffcompareWeek-1.png" alt="% difference in weekly mean PM2.5 levels 2020 vs 2017-2019, Southampton" width="672" />
<p class="caption">
Figure 9.6: % difference in weekly mean PM2.5 levels 2020 vs 2017-2019, Southampton
</p>
</div>
<blockquote>
<p>Beware seasonal trends and meteorological affects</p>
</blockquote>
</div>
<div id="wind-direction-and-speed" class="section level1">
<h1><span class="header-section-number">10</span> Wind direction and speed</h1>
<p>As noted above, air pollution levels in any given time period are highly dependent on the prevailing meteorological conditions.</p>
<p>Figure <a href="#fig:recentWind">10.1</a> shows the wind direction and speed over the period of lockdown and can be compared with the equivalent pollutant level plots above such as Figure <a href="#fig:no2recent">4.2</a>.</p>
<pre class="r"><code># windDT[, .(mean = mean(wd)), keyby = .(site)] # they&#39;re identical across AURN sites
windDirDT &lt;- fixedDT[pollutant == &quot;wd&quot; &amp; site %like% &quot;A33&quot;]
windDirDT[, `:=`(wd, value)]
setkey(windDirDT, dateTimeUTC, site, source)
windSpeedDT &lt;- fixedDT[pollutant == &quot;ws&quot; &amp; site %like% &quot;A33&quot;]
windSpeedDT[, `:=`(ws, value)]
setkey(windSpeedDT, dateTimeUTC, site, source)

windDT &lt;- windSpeedDT[windDirDT]
windDT[, `:=`(rTime, hms::as_hms(dateTimeUTC))]
p &lt;- ggplot2::ggplot(windDT[obsDate &gt; as.Date(&quot;2020-03-23&quot;)], aes(x = dateTimeUTC, y = ws, angle = -wd + 90, colour = ws)) + 
    geom_text(label = &quot;→&quot;) + theme(legend.position = &quot;bottom&quot;) + guides(colour = guide_legend(title = &quot;Wind speed&quot;)) + 
    scale_color_continuous(high = &quot;#132B43&quot;, low = &quot;#56B1F7&quot;)  # normal blue reversed


yMin &lt;- min(windDT[obsDate &gt; as.Date(&quot;2020-03-23&quot;)]$ws)
yMax &lt;- max(windDT[obsDate &gt; as.Date(&quot;2020-03-23&quot;)]$ws)
p &lt;- addWeekendsDateTime(p, yMin, yMax)
# p &lt;- addLockdownRectDateTime(p, yMin, yMax)
p &lt;- p + labs(y = &quot;Wind speed&quot;, x = &quot;Time&quot;, caption = paste0(myParams$weekendCap)) + theme(axis.text.x = element_text(angle = 90, 
    hjust = 1, size = 9))
p + xlim(lubridate::as_datetime(&quot;2020-03-23 23:59:59&quot;), NA)  # do this last otherwise adding the weekends takes the plot back to the earliest weekend we annotate</code></pre>
<div class="figure"><span id="fig:recentWind"></span>
<img src="sccAirQualExplore_covidLockdown2020_files/figure-html/recentWind-1.png" alt="Wind direction and speed in Southampton since 23rd March 2020" width="672" />
<p class="caption">
Figure 10.1: Wind direction and speed in Southampton since 23rd March 2020
</p>
</div>
<p>Figure <a href="#fig:recentWindRose">10.2</a> shows a <a href="https://www.rdocumentation.org/packages/openair/versions/2.7-2/topics/windRose">windrose</a> for each of the periods of low/high pollutant levels visible in Figure <a href="#fig:no2pcDiffcompareDay">4.5</a>:</p>
<ul>
<li>26 March - 4 April (lower NO2)</li>
<li>7 April - 12 April (higher NO2)</li>
<li>16 April - 23 April (lower NO2)</li>
</ul>
<p>The windroses indicate the direction the prevailing wind was blowing from and the colour of the 'paddles' indicates the strength while the length of the paddles indicates the proportion of observations. As we can see there are clear differences in the wind conditions which correlate with the pollution patterns observed:</p>
<ul>
<li>the first period with low NO2 was dominated by north-north easterly winds (likely to bring city and motorway air);</li>
<li>the second period when NO2 and particulates were high was dominated by low speed south easterly winds (bringing continental air);</li>
<li>the third period when NO2 was low was again dominated by north easterly winds.</li>
</ul>
<pre class="r"><code>fixedDT[, `:=`(aqPeriod, ifelse(obsDate &gt;= as.Date(&quot;2020-03-26&quot;) &amp; obsDate &lt;= as.Date(&quot;2020-04-04&quot;), &quot;Period 1 - Low: 26/3 - 4/4&quot;, 
    NA))]
fixedDT[, `:=`(aqPeriod, ifelse(obsDate &gt;= as.Date(&quot;2020-04-07&quot;) &amp; obsDate &lt;= as.Date(&quot;2020-04-12&quot;), &quot;Period 2 - High: 7/4 - 12/4&quot;, 
    aqPeriod))]
fixedDT[, `:=`(aqPeriod, ifelse(obsDate &gt;= as.Date(&quot;2020-04-16&quot;) &amp; obsDate &lt;= as.Date(&quot;2020-04-23&quot;), &quot;Period 3 - Low: 16/4 - 23/4&quot;, 
    aqPeriod))]

plotDT &lt;- fixedDT[!is.na(aqPeriod) &amp; (pollutant == &quot;ws&quot; | pollutant == &quot;wd&quot;) &amp; site %like% &quot;A33&quot;]

t &lt;- plotDT[, .(start = min(dateTimeUTC), end = max(dateTimeUTC)), keyby = .(aqPeriod)]

kableExtra::kable(t, caption = &quot;Check period start/end times&quot;) %&gt;% kable_styling()</code></pre>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:recentWindRose">Table 10.1: </span>Check period start/end times
</caption>
<thead>
<tr>
<th style="text-align:left;">
aqPeriod
</th>
<th style="text-align:left;">
start
</th>
<th style="text-align:left;">
end
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Period 1 - Low: 26/3 - 4/4
</td>
<td style="text-align:left;">
2020-03-26
</td>
<td style="text-align:left;">
2020-04-04 23:00:00
</td>
</tr>
<tr>
<td style="text-align:left;">
Period 2 - High: 7/4 - 12/4
</td>
<td style="text-align:left;">
2020-04-07
</td>
<td style="text-align:left;">
2020-04-12 23:00:00
</td>
</tr>
<tr>
<td style="text-align:left;">
Period 3 - Low: 16/4 - 23/4
</td>
<td style="text-align:left;">
2020-04-16
</td>
<td style="text-align:left;">
2020-04-23 23:00:00
</td>
</tr>
</tbody>
</table>
<pre class="r"><code># make a dt openair will accept
wdDT &lt;- plotDT[pollutant == &quot;wd&quot;, .(dateTimeUTC, site, wd = value, aqPeriod)]
setkey(wdDT, dateTimeUTC, site, aqPeriod)
wsDT &lt;- plotDT[pollutant == &quot;ws&quot;, .(dateTimeUTC, site, ws = value, aqPeriod)]
setkey(wsDT, dateTimeUTC, site, aqPeriod)
wrDT &lt;- wdDT[wsDT]
openair::windRose(wrDT, type = &quot;aqPeriod&quot;)</code></pre>
<div class="figure"><span id="fig:recentWindRose"></span>
<img src="sccAirQualExplore_covidLockdown2020_files/figure-html/recentWindRose-1.png" alt="Wind rose for Southampton sites since 23rd March 2020" width="672" />
<p class="caption">
Figure 10.2: Wind rose for Southampton sites since 23rd March 2020
</p>
</div>
</div>
<div id="save-data" class="section level1">
<h1><span class="header-section-number">11</span> Save data</h1>
<p>Save long form fixed-date data to <a href="../savedData/">savedData</a> for re-use.</p>
<pre class="r"><code>fixedDT[, `:=`(weekDay, lubridate::wday(dateTimeUTC, label = TRUE, abbr = TRUE))]
f &lt;- paste0(here::here(), &quot;/savedData/sotonExtract2017_2020_v2.csv&quot;)
data.table::fwrite(fixedDT, f)
dkUtils::gzipIt(f)</code></pre>
<p>Saved data description:</p>
<pre class="r"><code>skimr::skim(fixedDT)</code></pre>
<table style="width: auto;" class="table table-condensed">
<caption>
<span id="tab:dataSkim">Table 11.1: </span>Data summary
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:left;">
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Name
</td>
<td style="text-align:left;">
fixedDT
</td>
</tr>
<tr>
<td style="text-align:left;">
Number of rows
</td>
<td style="text-align:left;">
705536
</td>
</tr>
<tr>
<td style="text-align:left;">
Number of columns
</td>
<td style="text-align:left;">
19
</td>
</tr>
<tr>
<td style="text-align:left;">
_______________________
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
Column type frequency:
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
character
</td>
<td style="text-align:left;">
6
</td>
</tr>
<tr>
<td style="text-align:left;">
Date
</td>
<td style="text-align:left;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
factor
</td>
<td style="text-align:left;">
4
</td>
</tr>
<tr>
<td style="text-align:left;">
numeric
</td>
<td style="text-align:left;">
5
</td>
</tr>
<tr>
<td style="text-align:left;">
POSIXct
</td>
<td style="text-align:left;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
________________________
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
Group variables
</td>
<td style="text-align:left;">
None
</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: character</strong></p>
<table>
<thead>
<tr>
<th style="text-align:left;">
skim_variable
</th>
<th style="text-align:right;">
n_missing
</th>
<th style="text-align:right;">
complete_rate
</th>
<th style="text-align:right;">
min
</th>
<th style="text-align:right;">
max
</th>
<th style="text-align:right;">
empty
</th>
<th style="text-align:right;">
n_unique
</th>
<th style="text-align:right;">
whitespace
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
pollutant
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1.00
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
13
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
source
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1.00
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
8
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
site
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1.00
</td>
<td style="text-align:right;">
26
</td>
<td style="text-align:right;">
38
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
ratified
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1.00
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
compareYear
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1.00
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
9
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
aqPeriod
</td>
<td style="text-align:right;">
695980
</td>
<td style="text-align:right;">
0.01
</td>
<td style="text-align:right;">
26
</td>
<td style="text-align:right;">
27
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
0
</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: Date</strong></p>
<table>
<thead>
<tr>
<th style="text-align:left;">
skim_variable
</th>
<th style="text-align:right;">
n_missing
</th>
<th style="text-align:right;">
complete_rate
</th>
<th style="text-align:left;">
min
</th>
<th style="text-align:left;">
max
</th>
<th style="text-align:left;">
median
</th>
<th style="text-align:right;">
n_unique
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
obsDate
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:left;">
2017-01-01
</td>
<td style="text-align:left;">
2020-06-07
</td>
<td style="text-align:left;">
2018-09-02
</td>
<td style="text-align:right;">
1254
</td>
</tr>
<tr>
<td style="text-align:left;">
date2020
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:left;">
2020-01-01
</td>
<td style="text-align:left;">
2020-12-30
</td>
<td style="text-align:left;">
2020-06-06
</td>
<td style="text-align:right;">
365
</td>
</tr>
<tr>
<td style="text-align:left;">
fixedDate
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:left;">
2019-12-29
</td>
<td style="text-align:left;">
2020-12-29
</td>
<td style="text-align:left;">
2020-06-05
</td>
<td style="text-align:right;">
367
</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: factor</strong></p>
<table>
<thead>
<tr>
<th style="text-align:left;">
skim_variable
</th>
<th style="text-align:right;">
n_missing
</th>
<th style="text-align:right;">
complete_rate
</th>
<th style="text-align:left;">
ordered
</th>
<th style="text-align:right;">
n_unique
</th>
<th style="text-align:left;">
top_counts
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
origDoW
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:left;">
TRUE
</td>
<td style="text-align:right;">
7
</td>
<td style="text-align:left;">
Sat: 101713, Sun: 101470, Fri: 101241, Wed: 100565
</td>
</tr>
<tr>
<td style="text-align:left;">
day2020
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:left;">
TRUE
</td>
<td style="text-align:right;">
7
</td>
<td style="text-align:left;">
Wed: 111805, Mon: 101210, Tue: 101007, Fri: 100141
</td>
</tr>
<tr>
<td style="text-align:left;">
fixedDoW
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:left;">
TRUE
</td>
<td style="text-align:right;">
7
</td>
<td style="text-align:left;">
Sat: 101713, Sun: 101470, Fri: 101241, Wed: 100565
</td>
</tr>
<tr>
<td style="text-align:left;">
weekDay
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:left;">
TRUE
</td>
<td style="text-align:right;">
7
</td>
<td style="text-align:left;">
Sat: 101713, Sun: 101470, Fri: 101241, Wed: 100565
</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table>
<thead>
<tr>
<th style="text-align:left;">
skim_variable
</th>
<th style="text-align:right;">
n_missing
</th>
<th style="text-align:right;">
complete_rate
</th>
<th style="text-align:right;">
mean
</th>
<th style="text-align:right;">
sd
</th>
<th style="text-align:right;">
p0
</th>
<th style="text-align:right;">
p25
</th>
<th style="text-align:right;">
p50
</th>
<th style="text-align:right;">
p75
</th>
<th style="text-align:right;">
p100
</th>
<th style="text-align:left;">
hist
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
value
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
40.79
</td>
<td style="text-align:right;">
68.33
</td>
<td style="text-align:right;">
-9.6
</td>
<td style="text-align:right;">
4.83
</td>
<td style="text-align:right;">
15.59
</td>
<td style="text-align:right;">
42.00
</td>
<td style="text-align:right;">
1058.00
</td>
<td style="text-align:left;">
▇▁▁▁▁
</td>
</tr>
<tr>
<td style="text-align:left;">
year
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
2018.19
</td>
<td style="text-align:right;">
0.98
</td>
<td style="text-align:right;">
2017.0
</td>
<td style="text-align:right;">
2017.00
</td>
<td style="text-align:right;">
2018.00
</td>
<td style="text-align:right;">
2019.00
</td>
<td style="text-align:right;">
2020.00
</td>
<td style="text-align:left;">
▇▇▁▇▂
</td>
</tr>
<tr>
<td style="text-align:left;">
month
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
6.13
</td>
<td style="text-align:right;">
3.47
</td>
<td style="text-align:right;">
1.0
</td>
<td style="text-align:right;">
3.00
</td>
<td style="text-align:right;">
6.00
</td>
<td style="text-align:right;">
9.00
</td>
<td style="text-align:right;">
12.00
</td>
<td style="text-align:left;">
▇▅▅▅▆
</td>
</tr>
<tr>
<td style="text-align:left;">
decimalDate
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
2018.65
</td>
<td style="text-align:right;">
0.96
</td>
<td style="text-align:right;">
2017.0
</td>
<td style="text-align:right;">
2017.82
</td>
<td style="text-align:right;">
2018.67
</td>
<td style="text-align:right;">
2019.46
</td>
<td style="text-align:right;">
2020.43
</td>
<td style="text-align:left;">
▇▇▇▇▆
</td>
</tr>
<tr>
<td style="text-align:left;">
weekNo
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
24.79
</td>
<td style="text-align:right;">
15.15
</td>
<td style="text-align:right;">
1.0
</td>
<td style="text-align:right;">
12.00
</td>
<td style="text-align:right;">
23.00
</td>
<td style="text-align:right;">
38.00
</td>
<td style="text-align:right;">
53.00
</td>
<td style="text-align:left;">
▇▇▆▆▆
</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: POSIXct</strong></p>
<table>
<thead>
<tr>
<th style="text-align:left;">
skim_variable
</th>
<th style="text-align:right;">
n_missing
</th>
<th style="text-align:right;">
complete_rate
</th>
<th style="text-align:left;">
min
</th>
<th style="text-align:left;">
max
</th>
<th style="text-align:left;">
median
</th>
<th style="text-align:right;">
n_unique
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
dateTimeUTC
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:left;">
2017-01-01
</td>
<td style="text-align:left;">
2020-06-07 23:00:00
</td>
<td style="text-align:left;">
2018-09-02 20:00:00
</td>
<td style="text-align:right;">
30096
</td>
</tr>
</tbody>
</table>
<p>Saved data sites by year:</p>
<pre class="r"><code>t &lt;- table(fixedDT$site, fixedDT$year)

kableExtra::kable(t, caption = &quot;Sites available by year&quot;) %&gt;% kable_styling()</code></pre>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:dataYears">Table 11.2: </span>Sites available by year
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
2017
</th>
<th style="text-align:right;">
2018
</th>
<th style="text-align:right;">
2019
</th>
<th style="text-align:right;">
2020
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Southampton - Onslow Road (near RSH)
</td>
<td style="text-align:right;">
25307
</td>
<td style="text-align:right;">
25755
</td>
<td style="text-align:right;">
24762
</td>
<td style="text-align:right;">
6408
</td>
</tr>
<tr>
<td style="text-align:left;">
Southampton - Victoria Road (Woolston)
</td>
<td style="text-align:right;">
19251
</td>
<td style="text-align:right;">
23091
</td>
<td style="text-align:right;">
11541
</td>
<td style="text-align:right;">
6195
</td>
</tr>
<tr>
<td style="text-align:left;">
Southampton A33 (via AURN)
</td>
<td style="text-align:right;">
67278
</td>
<td style="text-align:right;">
62214
</td>
<td style="text-align:right;">
65751
</td>
<td style="text-align:right;">
24767
</td>
</tr>
<tr>
<td style="text-align:left;">
Southampton Centre (via AURN)
</td>
<td style="text-align:right;">
103806
</td>
<td style="text-align:right;">
100155
</td>
<td style="text-align:right;">
105871
</td>
<td style="text-align:right;">
33384
</td>
</tr>
</tbody>
</table>
<p>Saved pollutants by site:</p>
<pre class="r"><code>t &lt;- table(fixedDT$site, fixedDT$pollutant)

kableExtra::kable(t, caption = &quot;Pollutants available by site&quot;) %&gt;% kable_styling()</code></pre>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:dataSites">Table 11.3: </span>Pollutants available by site
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
no
</th>
<th style="text-align:right;">
no2
</th>
<th style="text-align:right;">
nox
</th>
<th style="text-align:right;">
nv10
</th>
<th style="text-align:right;">
nv2.5
</th>
<th style="text-align:right;">
o3
</th>
<th style="text-align:right;">
pm10
</th>
<th style="text-align:right;">
pm2.5
</th>
<th style="text-align:right;">
so2
</th>
<th style="text-align:right;">
v10
</th>
<th style="text-align:right;">
v2.5
</th>
<th style="text-align:right;">
wd
</th>
<th style="text-align:right;">
ws
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Southampton - Onslow Road (near RSH)
</td>
<td style="text-align:right;">
27412
</td>
<td style="text-align:right;">
27408
</td>
<td style="text-align:right;">
27412
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
Southampton - Victoria Road (Woolston)
</td>
<td style="text-align:right;">
20026
</td>
<td style="text-align:right;">
20026
</td>
<td style="text-align:right;">
20026
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
Southampton A33 (via AURN)
</td>
<td style="text-align:right;">
29641
</td>
<td style="text-align:right;">
29640
</td>
<td style="text-align:right;">
29640
</td>
<td style="text-align:right;">
23208
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
25681
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
23208
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
29496
</td>
<td style="text-align:right;">
29496
</td>
</tr>
<tr>
<td style="text-align:left;">
Southampton Centre (via AURN)
</td>
<td style="text-align:right;">
28657
</td>
<td style="text-align:right;">
28657
</td>
<td style="text-align:right;">
28658
</td>
<td style="text-align:right;">
21105
</td>
<td style="text-align:right;">
22627
</td>
<td style="text-align:right;">
28645
</td>
<td style="text-align:right;">
26180
</td>
<td style="text-align:right;">
27702
</td>
<td style="text-align:right;">
28261
</td>
<td style="text-align:right;">
21105
</td>
<td style="text-align:right;">
22627
</td>
<td style="text-align:right;">
29496
</td>
<td style="text-align:right;">
29496
</td>
</tr>
</tbody>
</table>
<p>NB:</p>
<ul>
<li>ws = wind speed</li>
<li>wd = wind direction</li>
<li>v* = volatiles</li>
</ul>
<p>We have also produced <a href="sccAirQualExplore_windroses_Wind%20and%20pollution%20roses%202016-2020%20(AURN%20data).html">wind/pollution roses</a> for these sites.</p>
</div>
<div id="about" class="section level1">
<h1><span class="header-section-number">12</span> About</h1>
<div id="code" class="section level2">
<h2><span class="header-section-number">12.1</span> Code</h2>
<p>Source:</p>
<ul>
<li><a href="https://github.com/dataknut/airQual" class="uri">https://github.com/dataknut/airQual</a></li>
</ul>
<p>History:</p>
<ul>
<li><a href="https://github.com/dataknut/airQual/commits/master" class="uri">https://github.com/dataknut/airQual/commits/master</a></li>
</ul>
</div>
<div id="comments-and-feedback" class="section level2">
<h2><span class="header-section-number">12.2</span> Comments and feedback</h2>
<p>If you wish to comment please open an issue:</p>
<ul>
<li><a href="https://github.com/dataknut/airQual/issues" class="uri">https://github.com/dataknut/airQual/issues</a></li>
</ul>
</div>
<div id="citation" class="section level2">
<h2><span class="header-section-number">12.3</span> Citation</h2>
<p>If you wish to refer to any of the material from this report please cite as:</p>
<ul>
<li>Anderson, B., (2020) Air Quality in Southampton (UK): Exploring the effect of UK covid 19 lockdown on air quality , <a href="http://www.energy.soton.ac.uk">Sustainable Energy Research Group</a>, University of Southampton: Southampton, UK.</li>
</ul>
<p>Report circulation:</p>
<ul>
<li>Public</li>
</ul>
<p>This work is (c) 2020 the University of Southampton and is part of a collection of <a href="https://dataknut.github.io/airQual/">air quality</a> data analyses.</p>
</div>
</div>
<div id="annex" class="section level1">
<h1><span class="header-section-number">13</span> Annex</h1>
<div id="annexMissing" class="section level2">
<h2><span class="header-section-number">13.1</span> Missing data</h2>
<p>Several of these datasets suffer from missing data or have stopped updating. This is visualised below for all data for all sites from January 2020.</p>
<p>For example <a href="#fig:testNegNo2">13.1</a> shows missing data patterns for Nitrogen Dioxide.</p>
<pre class="r"><code># dt,xvar, yvar,fillVar, yLab
yLab &lt;- &quot;NO2&quot;
tileDT &lt;- fixedDT[pollutant == &quot;no2&quot; &amp; dateTimeUTC &gt; as.Date(&quot;2020-02-01&quot;) &amp; !is.na(value)]
p &lt;- makeTilePlot(tileDT, xVar = &quot;dateTimeUTC&quot;, xLab = &quot;Date &amp; Time&quot;, yVar = &quot;site&quot;, fillVar = &quot;value&quot;, yLab = yLab)

p + scale_x_datetime(date_breaks = &quot;7 day&quot;, date_labels = &quot;%a %d %b&quot;) + theme(axis.text.x = element_text(angle = 90, 
    hjust = 1))</code></pre>
<div class="figure"><span id="fig:testNegNo2"></span>
<img src="sccAirQualExplore_covidLockdown2020_files/figure-html/testNegNo2-1.png" alt="Nitrogen Dioxide data availability and levels over time" width="672" />
<p class="caption">
Figure 13.1: Nitrogen Dioxide data availability and levels over time
</p>
</div>
<pre class="r"><code>yLab &lt;- &quot;NOx&quot;
# dt,xvar, yvar,fillVar, yLab
tileDT &lt;- fixedDT[pollutant == &quot;nox&quot; &amp; dateTimeUTC &gt; as.Date(&quot;2020-02-01&quot;) &amp; !is.na(value)]
p &lt;- makeTilePlot(tileDT, xVar = &quot;dateTimeUTC&quot;, xLab = &quot;Date &amp; Time&quot;, yVar = &quot;site&quot;, fillVar = &quot;value&quot;, yLab = yLab)

p + scale_x_datetime(date_breaks = &quot;7 day&quot;, date_labels = &quot;%a %d %b&quot;) + theme(axis.text.x = element_text(angle = 90, 
    hjust = 1))</code></pre>
<div class="figure"><span id="fig:testNegNox"></span>
<img src="sccAirQualExplore_covidLockdown2020_files/figure-html/testNegNox-1.png" alt="Oxides of nitrogen data availability and levels over time" width="672" />
<p class="caption">
Figure 13.2: Oxides of nitrogen data availability and levels over time
</p>
</div>
<pre class="r"><code>yLab &lt;- &quot;SO2&quot;
# dt,xvar, yvar,fillVar, yLab
tileDT &lt;- fixedDT[pollutant == &quot;so2&quot; &amp; dateTimeUTC &gt; as.Date(&quot;2020-02-01&quot;) &amp; !is.na(value)]
p &lt;- makeTilePlot(tileDT, xVar = &quot;dateTimeUTC&quot;, xLab = &quot;Date &amp; Time&quot;, yVar = &quot;site&quot;, fillVar = &quot;value&quot;, yLab = yLab)

p + scale_x_datetime(date_breaks = &quot;7 day&quot;, date_labels = &quot;%a %d %b&quot;) + theme(axis.text.x = element_text(angle = 90, 
    hjust = 1))</code></pre>
<div class="figure"><span id="fig:testNegSo2"></span>
<img src="sccAirQualExplore_covidLockdown2020_files/figure-html/testNegSo2-1.png" alt="Sulphour Dioxide data availability and levels over time" width="672" />
<p class="caption">
Figure 13.3: Sulphour Dioxide data availability and levels over time
</p>
</div>
<pre class="r"><code>yLab &lt;- &quot;O3&quot;
tileDT &lt;- fixedDT[pollutant == &quot;o3&quot; &amp; dateTimeUTC &gt; as.Date(&quot;2020-02-01&quot;) &amp; !is.na(value)]
p &lt;- makeTilePlot(tileDT, xVar = &quot;dateTimeUTC&quot;, xLab = &quot;Date &amp; Time&quot;, yVar = &quot;site&quot;, fillVar = &quot;value&quot;, yLab = yLab)

p + scale_x_datetime(date_breaks = &quot;7 day&quot;, date_labels = &quot;%a %d %b&quot;) + theme(axis.text.x = element_text(angle = 90, 
    hjust = 1))</code></pre>
<div class="figure"><span id="fig:testNego3"></span>
<img src="sccAirQualExplore_covidLockdown2020_files/figure-html/testNego3-1.png" alt="Availability and level of o3 data over time" width="672" />
<p class="caption">
Figure 13.4: Availability and level of o3 data over time
</p>
</div>
<pre class="r"><code>yLab &lt;- &quot;PM10&quot;
tileDT &lt;- fixedDT[pollutant == &quot;pm10&quot; &amp; dateTimeUTC &gt; as.Date(&quot;2020-02-01&quot;) &amp; !is.na(value)]
p &lt;- makeTilePlot(tileDT, xVar = &quot;dateTimeUTC&quot;, xLab = &quot;Date &amp; Time&quot;, yVar = &quot;site&quot;, fillVar = &quot;value&quot;, yLab = yLab)

p + scale_x_datetime(date_breaks = &quot;7 day&quot;, date_labels = &quot;%a %d %b&quot;) + theme(axis.text.x = element_text(angle = 90, 
    hjust = 1))</code></pre>
<div class="figure"><span id="fig:testNegPM10"></span>
<img src="sccAirQualExplore_covidLockdown2020_files/figure-html/testNegPM10-1.png" alt="Availability and level of PM 10 data over time" width="672" />
<p class="caption">
Figure 13.5: Availability and level of PM 10 data over time
</p>
</div>
<pre class="r"><code>yLab &lt;- &quot;PM2.5&quot;
tileDT &lt;- fixedDT[pollutant == &quot;pm2.5&quot; &amp; dateTimeUTC &gt; as.Date(&quot;2020-02-01&quot;) &amp; !is.na(value)]
p &lt;- makeTilePlot(tileDT, xVar = &quot;dateTimeUTC&quot;, xLab = &quot;Date &amp; Time&quot;, yVar = &quot;site&quot;, fillVar = &quot;value&quot;, yLab = yLab)

p + scale_x_datetime(date_breaks = &quot;7 day&quot;, date_labels = &quot;%a %d %b&quot;) + theme(axis.text.x = element_text(angle = 90, 
    hjust = 1))</code></pre>
<div class="figure"><span id="fig:testNegPM25"></span>
<img src="sccAirQualExplore_covidLockdown2020_files/figure-html/testNegPM25-1.png" alt="Availability and level of PM 2.5 data over time" width="672" />
<p class="caption">
Figure 13.6: Availability and level of PM 2.5 data over time
</p>
</div>
</div>
<div id="ship-activity" class="section level2">
<h2><span class="header-section-number">13.2</span> Ship activity</h2>
<p>Exploration of correlations between wind direction, recorded ship activity and pollutants.</p>
<p>Data:</p>
<ul>
<li>Air quality: AURN</li>
<li>Ship counts: Western docks forum</li>
<li>WHO reference thresholds: <a href="https://www.who.int/news-room/fact-sheets/detail/ambient-(outdoor)-air-quality-and-health" class="uri">https://www.who.int/news-room/fact-sheets/detail/ambient-(outdoor)-air-quality-and-health</a></li>
</ul>
<p>It is important to consider the relative locations of the air quality stations and the port activities when interpreting this data. The map below shows the rough location of the stations (coloured circles: green 2 = A33, orange 4 = City Centre) as well as the locations of monitoring stations that, as of June 4th 2020, are not collecting data.</p>
<div class="figure">
<img src="../figs/hantsAirLocs.png" alt="Latest air quality snaphot (June 4th 2020)" />
<p class="caption">Latest air quality snaphot (June 4th 2020)</p>
</div>
<pre class="r"><code>shipsDailyDT &lt;- data.table::fread(paste0(aqParams$SCCdataPath, &quot;/shipNumbers/shipNumbersSouthampton.csv&quot;))
shipsDailyDT[, `:=`(rDate, lubridate::dmy(Date))]
shipsDailyDT &lt;- shipsDailyDT[!is.na(rDate)]
# summary(shipsDailyDT$rDate)

shipsDailyDT[, `:=`(allShips, cargo + max_cruise)]
shipsDailyDT[, `:=`(allShipsCoded, ifelse(allShips == 0, &quot;0&quot;, NA))]
shipsDailyDT[, `:=`(allShipsCoded, ifelse(allShips == 1 | allShips == 2, &quot;1-2&quot;, allShipsCoded))]
shipsDailyDT[, `:=`(allShipsCoded, ifelse(allShips == 3 | allShips == 4, &quot;3-4&quot;, allShipsCoded))]
shipsDailyDT[, `:=`(allShipsCoded, ifelse(allShips == 5 | allShips == 6, &quot;5-6&quot;, allShipsCoded))]
shipsDailyDT[, `:=`(allShipsCoded, ifelse(allShips &gt; 6, &quot;7+&quot;, allShipsCoded))]

# re-code all ships to something more intuitive than openair does
shipsDailyDT[, `:=`(maxCruiseCoded, ifelse(max_cruise == 0, &quot;0&quot;, NA))]
shipsDailyDT[, `:=`(maxCruiseCoded, ifelse(max_cruise == 1 | max_cruise == 2, &quot;1-2&quot;, maxCruiseCoded))]
shipsDailyDT[, `:=`(maxCruiseCoded, ifelse(max_cruise == 3 | max_cruise == 4, &quot;3-4&quot;, maxCruiseCoded))]
shipsDailyDT[, `:=`(maxCruiseCoded, ifelse(max_cruise &gt; 4, &quot;5+&quot;, maxCruiseCoded))]
t &lt;- with(shipsDailyDT, table(maxCruiseCoded, allShipsCoded))

kableExtra::kable(addmargins(t), caption = &quot;Number of days with max n cruise ships (rows) vs all ships&quot;) %&gt;% kable_styling()</code></pre>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:loadShipsData">Table 13.1: </span>Number of days with max n cruise ships (rows) vs all ships
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
1-2
</th>
<th style="text-align:right;">
3-4
</th>
<th style="text-align:right;">
5-6
</th>
<th style="text-align:right;">
7+
</th>
<th style="text-align:right;">
Sum
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
1-2
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
4
</td>
</tr>
<tr>
<td style="text-align:left;">
3-4
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
15
</td>
<td style="text-align:right;">
12
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
30
</td>
</tr>
<tr>
<td style="text-align:left;">
5+
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
14
</td>
<td style="text-align:right;">
12
</td>
<td style="text-align:right;">
26
</td>
</tr>
<tr>
<td style="text-align:left;">
Sum
</td>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
15
</td>
<td style="text-align:right;">
26
</td>
<td style="text-align:right;">
15
</td>
<td style="text-align:right;">
61
</td>
</tr>
</tbody>
</table>
<pre class="r"><code>dailyNO2DT &lt;- no2dt[obsDate &gt;= as.Date(&quot;2020-04-01&quot;), .(meanNO2 = mean(value), maxNO2 = max(value), nObs = .N), 
    keyby = .(site, rDate = obsDate)]
dailyPM10DT &lt;- pm10dt[obsDate &gt;= as.Date(&quot;2020-04-01&quot;), .(meanPM10 = mean(value), maxPM10 = max(value), nObs = .N), 
    keyby = .(site, rDate = obsDate)]
# summary(dailyNO2DT$rDate)

windDirDT &lt;- fixedDT[pollutant == &quot;wd&quot;, .(site, dateTimeUTC, wd = value)]
windSpeedDT &lt;- fixedDT[pollutant == &quot;ws&quot;, .(site, dateTimeUTC, ws = value)]
setkey(windDirDT, site, dateTimeUTC)
setkey(windSpeedDT, site, dateTimeUTC)
windDT &lt;- windSpeedDT[windDirDT]
dailyWindDT &lt;- windDT[dateTimeUTC &gt;= as.Date(&quot;2020-04-01&quot;), .(meanWd = mean(wd), meanWs = mean(ws), nObs = .N), 
    keyby = .(site, rDate = as.Date(dateTimeUTC))]


setkey(shipsDailyDT, rDate)
setkey(dailyNO2DT, rDate)
setkey(dailyPM10DT, rDate)

plotNO2DT &lt;- shipsDailyDT[dailyNO2DT]
plotNO2DT &lt;- plotNO2DT[!is.na(cruise)]  # filter out

plotPM10DT &lt;- shipsDailyDT[dailyPM10DT]
plotPM10DT &lt;- plotPM10DT[!is.na(cruise)]  # filter out

setkey(dailyWindDT, site, rDate)
setkey(plotNO2DT, site, rDate)
plotNO2DT &lt;- dailyWindDT[plotNO2DT[site %like% &quot;AURN&quot;]]  # keep AURN only

setkey(dailyWindDT, site, rDate)
setkey(plotPM10DT, site, rDate)
plotPM10DT &lt;- dailyWindDT[plotPM10DT[site %like% &quot;AURN&quot;]]  # keep AURN only
# nrow(plotDT)</code></pre>
<p>Table <a href="#tab:loadShipsData">13.1</a> shows the number of days for which there are different maximum numbers of cruise ships (rows) and total cargo and cruise ships (columns). There is only 1 day when there are 0 cruise ships and no days when there are 0 ships. The sparseness of the data (only 61 days) and the relative lack of variation in ship numbers means that a relationship between ship numbers and pollution will be difficult to detect.</p>
<blockquote>
<p>In addition, and most importantly, these analyses only show correlations. It it quite possible, for example, that higher pollution levels are due to prevailing environmental/meteorological conditions that happen to coincide with more ships.</p>
</blockquote>
<div id="no2" class="section level3">
<h3><span class="header-section-number">13.2.1</span> NO2</h3>
<p>Figures <a href="#fig:meanNo2BoxPlotsCruise">13.7</a> and <a href="#fig:maxNo2BoxPlotsCruise">13.8</a> shows the distribution of mean and max daily NO2 by maximum cruise ship counts for the day. There are no clear relationships.</p>
<pre class="r"><code>myCap &lt;- &quot;April &amp; May 2020 \nSources: AURN hourly observations &amp; Western docks forum&quot;

ggplot2::ggplot(plotNO2DT, aes(x = maxCruiseCoded, y = meanNO2, group = maxCruiseCoded, color = site)) + geom_boxplot() + 
    labs(x = &quot;Max number of cruise ships&quot;, y = &quot;Mean daily NO2&quot;, caption = myCap) + facet_grid(. ~ site)</code></pre>
<div class="figure"><span id="fig:meanNo2BoxPlotsCruise"></span>
<img src="sccAirQualExplore_covidLockdown2020_files/figure-html/meanNo2BoxPlotsCruise-1.png" alt="Box plots of daily mean NO2 by maximum cruise ship counts" width="672" />
<p class="caption">
Figure 13.7: Box plots of daily mean NO2 by maximum cruise ship counts
</p>
</div>
<pre class="r"><code>ggplot2::ggplot(plotNO2DT, aes(x = maxCruiseCoded, y = maxNO2, group = maxCruiseCoded, color = site)) + geom_boxplot() + 
    labs(x = &quot;Max number of cruise ships&quot;, y = &quot;Max daily NO2&quot;, caption = paste0(myCap, &quot;\nReference line: WHO hourly threshold&quot;)) + 
    facet_grid(. ~ site) + geom_hline(yintercept = myParams$hourlyNo2Threshold_WHO)</code></pre>
<div class="figure"><span id="fig:maxNo2BoxPlotsCruise"></span>
<img src="sccAirQualExplore_covidLockdown2020_files/figure-html/maxNo2BoxPlotsCruise-1.png" alt="Box plots of daily max NO2 by maximum cruise ship counts" width="672" />
<p class="caption">
Figure 13.8: Box plots of daily max NO2 by maximum cruise ship counts
</p>
</div>
<p>Figures <a href="#fig:meanNo2BoxPlotsAll">13.9</a> and <a href="#fig:maxNo2BoxPlotsAll">13.10</a> repeats this for all ships. In this case there appears to be slightly more of a rising trend as the number of ships increases.</p>
<pre class="r"><code>ggplot2::ggplot(plotNO2DT, aes(x = allShipsCoded, y = meanNO2, group = allShipsCoded, color = site)) + geom_boxplot() + 
    labs(x = &quot;Max number of ships&quot;, y = &quot;Mean daily NO2 (hourly observations)&quot;, caption = myCap) + facet_grid(. ~ 
    site)</code></pre>
<div class="figure"><span id="fig:meanNo2BoxPlotsAll"></span>
<img src="sccAirQualExplore_covidLockdown2020_files/figure-html/meanNo2BoxPlotsAll-1.png" alt="Box plots of daily mean NO2 by cargo + cruise ship counts" width="672" />
<p class="caption">
Figure 13.9: Box plots of daily mean NO2 by cargo + cruise ship counts
</p>
</div>
<pre class="r"><code>ggplot2::ggplot(plotNO2DT, aes(x = allShipsCoded, y = maxNO2, group = allShipsCoded, color = site)) + geom_boxplot() + 
    labs(x = &quot;Max number of ships&quot;, y = &quot;Max daily NO2 (hourly observations)&quot;, caption = paste0(myCap, &quot;\nReference line: WHO hourly threshold&quot;)) + 
    facet_grid(. ~ site) + geom_hline(yintercept = myParams$hourlyNo2Threshold_WHO)</code></pre>
<div class="figure"><span id="fig:maxNo2BoxPlotsAll"></span>
<img src="sccAirQualExplore_covidLockdown2020_files/figure-html/maxNo2BoxPlotsAll-1.png" alt="Box plots of daily max NO2 by cargo + cruise ship counts" width="672" />
<p class="caption">
Figure 13.10: Box plots of daily max NO2 by cargo + cruise ship counts
</p>
</div>
<p>Figures <a href="#fig:meanNO2pollutionRoseCruise">13.11</a> and <a href="#fig:maxNO2pollutionRoseCruise">13.12</a> show <a href="https://davidcarslaw.github.io/openair/reference/windRose.html">pollution roses</a> for daily mean and daily max NO2 by the maximum number of cruise ships alongside per day. These show the most frequent wind directions (wind rose) overlain by the proportion of pollution concentrations in the calculated groups.</p>
<p>It appears that when the wind is from the South East/East <em>and</em> more cruise ships are alongside then higher levels of NO2 are more frequent. <strong>But</strong> this could also be due to wind-blown continental pollution when the wind is from this direction as was known to be the case <a href="https://airqualitynews.com/2020/04/07/people-at-risk-from-coronavirus-warned-with-very-high-air-pollution-episode-predicted-for-uk/">during April 2020</a>.</p>
<pre class="r"><code>plotNO2DT[, `:=`(wd, meanWd)]
plotNO2DT[, `:=`(ws, meanWs)]
plotNO2DT[site %like% &quot;A33&quot;, `:=`(shortSite, &quot;A33&quot;)]
plotNO2DT[site %like% &quot;Centre&quot;, `:=`(shortSite, &quot;Centre&quot;)]

openair::pollutionRose(plotNO2DT[max_cruise != 0], pollutant = &quot;meanNO2&quot;, type = c(&quot;maxCruiseCoded&quot;, &quot;shortSite&quot;))</code></pre>
<div class="figure"><span id="fig:meanNO2pollutionRoseCruise"></span>
<img src="sccAirQualExplore_covidLockdown2020_files/figure-html/meanNO2pollutionRoseCruise-1.png" alt="Pollution rose for mean NO2 for April &amp; May 2020 by max number of cruise ships (AURN sites, single day with 0 cruise ships excluded)" width="672" />
<p class="caption">
Figure 13.11: Pollution rose for mean NO2 for April &amp; May 2020 by max number of cruise ships (AURN sites, single day with 0 cruise ships excluded)
</p>
</div>
<pre class="r"><code>openair::pollutionRose(plotNO2DT[max_cruise != 0], pollutant = &quot;maxNO2&quot;, type = c(&quot;maxCruiseCoded&quot;, &quot;shortSite&quot;))</code></pre>
<div class="figure"><span id="fig:maxNO2pollutionRoseCruise"></span>
<img src="sccAirQualExplore_covidLockdown2020_files/figure-html/maxNO2pollutionRoseCruise-1.png" alt="Pollution rose for max NO2 for April &amp; May 2020 by max number of cruise ships (AURN sites, single day with 0 cruise ships excluded)" width="672" />
<p class="caption">
Figure 13.12: Pollution rose for max NO2 for April &amp; May 2020 by max number of cruise ships (AURN sites, single day with 0 cruise ships excluded)
</p>
</div>
<p>Figures <a href="#fig:meanNO2pollutionRoseAll">13.13</a> and <a href="#fig:maxNO2pollutionRoseAll">13.14</a> show pollution roses for daily mean and daily max NO2 by the number of all ships alongside per day. As we would expect, these plots appear to show a similar effect.</p>
<pre class="r"><code>openair::pollutionRose(plotNO2DT, pollutant = &quot;meanNO2&quot;, type = c(&quot;allShipsCoded&quot;, &quot;shortSite&quot;))</code></pre>
<div class="figure"><span id="fig:meanNO2pollutionRoseAll"></span>
<img src="sccAirQualExplore_covidLockdown2020_files/figure-html/meanNO2pollutionRoseAll-1.png" alt="Pollution rose for mean NO2 for April &amp; May 2020 by number of cruise + cargo ships (AURN sites)" width="672" />
<p class="caption">
Figure 13.13: Pollution rose for mean NO2 for April &amp; May 2020 by number of cruise + cargo ships (AURN sites)
</p>
</div>
<pre class="r"><code>openair::pollutionRose(plotNO2DT, pollutant = &quot;maxNO2&quot;, type = c(&quot;allShipsCoded&quot;, &quot;shortSite&quot;))</code></pre>
<div class="figure"><span id="fig:maxNO2pollutionRoseAll"></span>
<img src="sccAirQualExplore_covidLockdown2020_files/figure-html/maxNO2pollutionRoseAll-1.png" alt="Pollution rose for max NO2 for April &amp; May 2020 by number of cruise + cargo ships (AURN sites)" width="672" />
<p class="caption">
Figure 13.14: Pollution rose for max NO2 for April &amp; May 2020 by number of cruise + cargo ships (AURN sites)
</p>
</div>
</div>
<div id="pm10" class="section level3">
<h3><span class="header-section-number">13.2.2</span> PM10</h3>
<p>Figures <a href="#fig:meanPm10BoxPlots">13.15</a> and <a href="#fig:maxPm10BoxPlots">13.16</a> show the distribution of mean and max daily PM10 by maximum cruise ship counts for the day. There is no clear relationship.</p>
<pre class="r"><code>ggplot2::ggplot(plotPM10DT, aes(x = maxCruiseCoded, y = meanPM10, group = maxCruiseCoded, color = site)) + geom_boxplot() + 
    labs(x = &quot;Max number of cruise ships&quot;, y = &quot;Mean daily PM10&quot;, caption = paste0(myCap, &quot;\nReference line: WHO 24 hour mean threshold&quot;)) + 
    facet_grid(. ~ site) + geom_hline(yintercept = myParams$dailyPm10Threshold_WHO)</code></pre>
<div class="figure"><span id="fig:meanPm10BoxPlots"></span>
<img src="sccAirQualExplore_covidLockdown2020_files/figure-html/meanPm10BoxPlots-1.png" alt="Box plots of daily mean PM10 by maximum cruise ship counts" width="672" />
<p class="caption">
Figure 13.15: Box plots of daily mean PM10 by maximum cruise ship counts
</p>
</div>
<pre class="r"><code>ggplot2::ggplot(plotPM10DT, aes(x = maxCruiseCoded, y = maxPM10, group = maxCruiseCoded, color = site)) + geom_boxplot() + 
    labs(x = &quot;Max number of cruise ships&quot;, y = &quot;Max daily PM10&quot;, caption = myCap) + facet_grid(. ~ site)</code></pre>
<div class="figure"><span id="fig:maxPm10BoxPlots"></span>
<img src="sccAirQualExplore_covidLockdown2020_files/figure-html/maxPm10BoxPlots-1.png" alt="Box plots of daily max PM10 by maximum cruise ship counts" width="672" />
<p class="caption">
Figure 13.16: Box plots of daily max PM10 by maximum cruise ship counts
</p>
</div>
<p>Figures <a href="#fig:meanPm10BoxPlotsAll">13.17</a> and <a href="#fig:maxPm10BoxPlotsAll">13.18</a> repeat this for all ships. In this case there appears to be a stronger relationship.</p>
<pre class="r"><code>myCap &lt;- &quot;April &amp; May 2020 (Sources: AURN &amp; Western docks forum)&quot;

ggplot2::ggplot(plotPM10DT, aes(x = allShipsCoded, y = meanPM10, group = allShipsCoded, color = site)) + geom_boxplot() + 
    labs(x = &quot;Max number of ships&quot;, y = &quot;Mean daily PM10&quot;, caption = paste0(myCap, &quot;\nReference line: WHO 24 hour mean threshold&quot;)) + 
    facet_grid(. ~ site) + geom_hline(yintercept = myParams$dailyPm10Threshold_WHO)</code></pre>
<div class="figure"><span id="fig:meanPm10BoxPlotsAll"></span>
<img src="sccAirQualExplore_covidLockdown2020_files/figure-html/meanPm10BoxPlotsAll-1.png" alt="Box plots of daily mean PM10 by cargo + cruise ship counts" width="672" />
<p class="caption">
Figure 13.17: Box plots of daily mean PM10 by cargo + cruise ship counts
</p>
</div>
<pre class="r"><code>ggplot2::ggplot(plotPM10DT, aes(x = allShipsCoded, y = maxPM10, group = allShipsCoded, color = site)) + geom_boxplot() + 
    labs(x = &quot;Max number of ships&quot;, y = &quot;Max daily PM10 &quot;, caption = myCap) + facet_grid(. ~ site)</code></pre>
<div class="figure"><span id="fig:maxPm10BoxPlotsAll"></span>
<img src="sccAirQualExplore_covidLockdown2020_files/figure-html/maxPm10BoxPlotsAll-1.png" alt="Box plots of daily max PM10 by cargo + cruise ship counts" width="672" />
<p class="caption">
Figure 13.18: Box plots of daily max PM10 by cargo + cruise ship counts
</p>
</div>
<p>Figures <a href="#fig:meanPm10pollutionRoseCruise">13.19</a> and <a href="#fig:maxPm10pollutionRoseCruise">13.20</a> show pollution roses for daily mean and daily max PM10 by the maximum number of cruise ships alongside per day.</p>
<p>It appears that when the wind is from the South East/East <em>and</em> more cruise ships are alongside then higher levels of PM10 are more frequent. But this is also the case when the wind is from the West in the 3-4 ships category.</p>
<pre class="r"><code>plotPM10DT[, `:=`(wd, meanWd)]
plotPM10DT[, `:=`(ws, meanWs)]
plotPM10DT[site %like% &quot;A33&quot;, `:=`(shortSite, &quot;A33&quot;)]
plotPM10DT[site %like% &quot;Centre&quot;, `:=`(shortSite, &quot;Centre&quot;)]

openair::pollutionRose(plotPM10DT[max_cruise != 0], pollutant = &quot;meanPM10&quot;, type = c(&quot;maxCruiseCoded&quot;, &quot;shortSite&quot;))</code></pre>
<div class="figure"><span id="fig:meanPm10pollutionRoseCruise"></span>
<img src="sccAirQualExplore_covidLockdown2020_files/figure-html/meanPm10pollutionRoseCruise-1.png" alt="Pollution roses for mean PM10 for April &amp; May 2020 by max number of cruise ships (AURN sites, single day with 0 cruise ships excluded)" width="672" />
<p class="caption">
Figure 13.19: Pollution roses for mean PM10 for April &amp; May 2020 by max number of cruise ships (AURN sites, single day with 0 cruise ships excluded)
</p>
</div>
<pre class="r"><code>openair::pollutionRose(plotPM10DT[max_cruise != 0], pollutant = &quot;maxPM10&quot;, type = c(&quot;maxCruiseCoded&quot;, &quot;shortSite&quot;))</code></pre>
<div class="figure"><span id="fig:maxPm10pollutionRoseCruise"></span>
<img src="sccAirQualExplore_covidLockdown2020_files/figure-html/maxPm10pollutionRoseCruise-1.png" alt="Pollution roses for max PM10 for April &amp; May 2020 by max number of cruise ships (AURN sites, single day with 0 cruise ships excluded)" width="672" />
<p class="caption">
Figure 13.20: Pollution roses for max PM10 for April &amp; May 2020 by max number of cruise ships (AURN sites, single day with 0 cruise ships excluded)
</p>
</div>
<p>Finally, Figures <a href="#fig:meanPm10pollutionRoseAll">13.21</a> and Figures <a href="#fig:maxPm10pollutionRoseAll">13.22</a> show a pollution rose for daily mean and daily max PM10 by the number of all ships alongside per day. These plots appear to show a similar effect. As before it is not possible to discount the potential confounding effects of overall environmental conditions which the South East and Easterly wind directions can produce.</p>
<pre class="r"><code>openair::pollutionRose(plotPM10DT, pollutant = &quot;meanPM10&quot;, type = c(&quot;allShipsCoded&quot;, &quot;shortSite&quot;))</code></pre>
<div class="figure"><span id="fig:meanPm10pollutionRoseAll"></span>
<img src="sccAirQualExplore_covidLockdown2020_files/figure-html/meanPm10pollutionRoseAll-1.png" alt="Pollution roses for mean PM10 for April &amp; May 2020 by number of cruise + cargo ships (AURN sites)" width="672" />
<p class="caption">
Figure 13.21: Pollution roses for mean PM10 for April &amp; May 2020 by number of cruise + cargo ships (AURN sites)
</p>
</div>
<pre class="r"><code>openair::pollutionRose(plotPM10DT, pollutant = &quot;maxPM10&quot;, type = c(&quot;allShipsCoded&quot;, &quot;shortSite&quot;))</code></pre>
<div class="figure"><span id="fig:maxPm10pollutionRoseAll"></span>
<img src="sccAirQualExplore_covidLockdown2020_files/figure-html/maxPm10pollutionRoseAll-1.png" alt="Pollution roses for max PM10 for April &amp; May 2020 by number of cruise + cargo ships (AURN sites)" width="672" />
<p class="caption">
Figure 13.22: Pollution roses for max PM10 for April &amp; May 2020 by number of cruise + cargo ships (AURN sites)
</p>
</div>
</div>
<div id="focus-on-south-to-east-winds" class="section level3">
<h3><span class="header-section-number">13.2.3</span> Focus on South to East winds</h3>
<p>Given the above pollution rose analysis it is worth repeating the max NO2 and max PM10 box plots but splitting the data by wind quadrant. Note that this still does not remove the potential confounding effect of continental air...</p>
<p>To do this we code the wind direction as:</p>
<ul>
<li>&quot;Q1: N -&gt; ENE&quot; wind from 0 - 70 degrees</li>
<li>&quot;Q2: ENE -&gt; S&quot; 70 - 180</li>
<li>&quot;Q3-4: S -&gt; N&quot; 180 - 360</li>
</ul>
<p>Figure <a href="#fig:quadrantMeanNO2">13.23</a> shows mean NO2 split by wind quadrant and site while <a href="#fig:quadrantMeanPM10">13.24</a> shows mean PM10. Unfortunately the number of observations are so small that we really cannot see any pattern.</p>
<pre class="r"><code>setWindQuad &lt;- function(dt) {
    # assumes wd = degrees openair default is 30 degrees
    dt[, `:=`(windDir, ifelse(wd &gt;= 0 &amp; wd &lt; 70, &quot;Q1: N -&gt; ENE&quot;, NA))]
    dt[, `:=`(windDir, ifelse(wd &gt;= 70 &amp; wd &lt; 180, &quot;Q2: ENE -&gt; S&quot;, windDir))]
    dt[, `:=`(windDir, ifelse(wd &gt;= 180 &amp; wd &lt; 360, &quot;Q3-4: S -&gt; N&quot;, windDir))]
    return(dt)
}
plotNO2DT &lt;- setWindQuad(plotNO2DT)

ggplot2::ggplot(plotNO2DT, aes(x = allShipsCoded, y = meanNO2, group = maxCruiseCoded, color = site)) + geom_boxplot() + 
    labs(x = &quot;Max number of ships&quot;, y = &quot;Mean daily NO2&quot;, caption = myCap) + facet_grid(windDir ~ site)</code></pre>
<div class="figure"><span id="fig:quadrantMeanNO2"></span>
<img src="sccAirQualExplore_covidLockdown2020_files/figure-html/quadrantMeanNO2-1.png" alt="Mean daily NO2 by wind quadrant and total ships" width="672" />
<p class="caption">
Figure 13.23: Mean daily NO2 by wind quadrant and total ships
</p>
</div>
<pre class="r"><code>plotPM10DT &lt;- setWindQuad(plotPM10DT)

ggplot2::ggplot(plotPM10DT, aes(x = allShipsCoded, y = meanPM10, group = maxCruiseCoded, color = site)) + geom_boxplot() + 
    labs(x = &quot;Max number of ships&quot;, y = &quot;Mean daily PM10&quot;, caption = myCap) + facet_grid(windDir ~ site)</code></pre>
<div class="figure"><span id="fig:quadrantMeanPM10"></span>
<img src="sccAirQualExplore_covidLockdown2020_files/figure-html/quadrantMeanPM10-1.png" alt="Mean daily PM10 by wind quadrant and total ships" width="672" />
<p class="caption">
Figure 13.24: Mean daily PM10 by wind quadrant and total ships
</p>
</div>
</div>
<div id="models" class="section level3">
<h3><span class="header-section-number">13.2.4</span> Models</h3>
<p>It is not clear that linear modelling is an appropriate method to use since the observations are not independent - the value at time t is closely related to the value at time t + 1.</p>
<pre class="r"><code># Need to convert to wide so we can subtract centre (backround)
table(fixedDT$site)</code></pre>
<pre><code>## 
##   Southampton - Onslow Road\n(near RSH) Southampton - Victoria Road\n(Woolston) 
##                                   82232                                   60078 
##             Southampton A33\n(via AURN)          Southampton Centre\n(via AURN) 
##                                  220010                                  343216</code></pre>
<pre class="r"><code>fixedDT[, shortSite := ifelse(site %like% &quot;A33&quot;, &quot;A33&quot;, &quot;Centre&quot;)]
a33DT &lt;- fixedDT[site %like% &quot;A33&quot; &amp; year &gt; 2019, .(dateTimeUTC, obsDate, shortSite, pollutant, value)]
centreDT &lt;- fixedDT[site %like% &quot;Centre&quot; &amp; year &gt; 2019, .(dateTimeUTC, obsDate, shortSite, pollutant, value)]

a33DTw &lt;- dcast(a33DT, dateTimeUTC + shortSite ~ pollutant + shortSite, 
                value.var = &quot;value&quot;)
centreDTw &lt;- dcast(centreDT, dateTimeUTC + shortSite ~ pollutant + shortSite, 
                value.var = &quot;value&quot;)

a33DTw[,shortSite := NULL] # don&#39;t need
setkey(a33DTw, dateTimeUTC)
centreDTw[,shortSite := NULL]
setkey(centreDTw, dateTimeUTC)

wideFixedDT &lt;- a33DTw[centreDTw]

# differencing - treat Centre as &#39;background&#39;

wideFixedDT[, NO2_A33diff := no2_A33 - no2_Centre]
wideFixedDT[, obsDate := as.Date(dateTimeUTC)]
wideDailyDT &lt;- wideFixedDT[, .(no2_A33 = mean(no2_A33),
                               pm10_A33 = mean(pm10_A33),
                               no2_Centre = mean(no2_Centre),
                               pm10_Centre = mean(pm10_Centre),
                               wd = mean(wd_A33), # these will be the same
                               ws = mean(ws_A33)
                               ), keyby = .(obsDate)
                           ]
wideDailyDT[,NO2_A33diff := no2_A33 - no2_Centre]
plotDT &lt;- wideDailyDT[shipsDailyDT]</code></pre>
<p>In any case the table below shows the results of estimating a linear regression model of:</p>
<ul>
<li>NO2 (A33 site) = total ships * wind quadrant</li>
</ul>
<p>This should show:</p>
<ul>
<li>the overall effects of total ships and wind quadrants</li>
<li>what effect of the interaction between total ships and wind quadrant has</li>
</ul>
<p>The results are more or less what we would expect given the small number of observations:</p>
<ul>
<li>the more ships there are, the lower the NO2 at the A33 site but this is not statistically significant (95% confidence intervals include 0);</li>
<li>compared to the N -&gt; ENE (contrast category omitted from the results), the ENE -&gt; S wind quadrant is associated with nearly 8 times lower NO2 at the A33 site but this is not statistically significant;</li>
<li>if the wind is ENE -&gt; S then every extra ship increased NO2 at the A33 site by 5 units but this is also not statistically significant</li>
</ul>
<pre class="r"><code>plotDT &lt;- setWindQuad(plotDT)
plotDT[, `:=`(date, obsDate)]
# openair::linearRelation(plotDT, x =&#39;no2_Centre&#39;, y = &#39;no2_A33&#39;)

lmA33 &lt;- lm(no2_A33 ~ allShips * windDir, plotDT)

stargazer::stargazer(lmA33, type = &quot;text&quot;, title = &quot;Model results&quot;, ci = TRUE, single.row = TRUE)</code></pre>
<pre><code>## 
## Model results
## ========================================================
##                                  Dependent variable:    
##                              ---------------------------
##                                        no2_A33          
## --------------------------------------------------------
## allShips                       -2.175 (-9.407, 5.058)   
## windDirQ2: ENE -&gt; S           -7.997 (-59.622, 43.627)  
## windDirQ3-4: S -&gt; N           -13.292 (-64.928, 38.343) 
## allShips:windDirQ2: ENE -&gt; S   5.433 (-2.409, 13.275)   
## allShips:windDirQ3-4: S -&gt; N   3.687 (-4.677, 12.050)   
## Constant                      24.643 (-24.070, 73.357)  
## --------------------------------------------------------
## Observations                             59             
## R2                                      0.402           
## Adjusted R2                             0.345           
## Residual Std. Error               14.074 (df = 53)      
## F Statistic                     7.117*** (df = 5; 53)   
## ========================================================
## Note:                        *p&lt;0.1; **p&lt;0.05; ***p&lt;0.01</code></pre>
<pre class="r"><code># do not run - fails The &#39;car&#39; package has some nice graphs to help here
car::qqPlot(lmA33)  # shows default 95% CI
car::spreadLevelPlot(lmA33)
message(&quot;# Do we think the variance of the residuals is constant?&quot;)
message(&quot;# Did the plot suggest a transformation?&quot;)</code></pre>
<pre class="r"><code>message(&quot;# autocorrelation/independence of errors&quot;)
car::durbinWatsonTest(lmA33)</code></pre>
<pre><code>##  lag Autocorrelation D-W Statistic p-value
##    1       0.2917613      1.333547   0.004
##  Alternative hypothesis: rho != 0</code></pre>
<pre class="r"><code>message(&quot;# if p &lt; 0.05 then a problem as implies autocorrelation ut beware small samples&quot;)</code></pre>
<p>However the diagnostic durbinWatsonTest test suggests autocorrelation, as we would expect. This means the standard errors are likely to be underestimates and so the confidence intervals are too narrow.</p>
<pre class="r"><code>message(&quot;# homoskedasticity: plot (should be no obvious pattern&quot;)
plot(plotDT[!is.na(no2_A33)]$no2_A33, lmA33$residuals)
abline(h = mean(lmA33$residuals), col = &quot;red&quot;)  # add the mean of the residuals (yay, it&#39;s zero!)</code></pre>
<p><img src="sccAirQualExplore_covidLockdown2020_files/figure-html/A33homoskedasticity-1.png" width="672" /></p>
<pre class="r"><code>message(&quot;# homoskedasticity: formal test&quot;)
car::ncvTest(lmA33)</code></pre>
<pre><code>## Non-constant Variance Score Test 
## Variance formula: ~ fitted.values 
## Chisquare = 11.63323, Df = 1, p = 0.00064784</code></pre>
<pre class="r"><code>message(&quot;# if p &gt; 0.05 then there is heteroskedasticity&quot;)</code></pre>
<pre class="r"><code>message(&quot;# -&gt; collinearity&quot;)
car::vif(lmA33)</code></pre>
<pre><code>##                       GVIF Df GVIF^(1/(2*Df))
## allShips          13.84555  1        3.720961
## windDir          261.64036  2        4.021853
## allShips:windDir 216.21918  2        3.834631</code></pre>
<pre class="r"><code># if any values &gt; 10 -&gt; problem
message(&quot;# -&gt; tolerance&quot;)
1/car::vif(lmA33)</code></pre>
<pre><code>##                         GVIF  Df GVIF^(1/(2*Df))
## allShips         0.072225368 1.0       0.2687478
## windDir          0.003822040 0.5       0.2486416
## allShips:windDir 0.004624937 0.5       0.2607813</code></pre>
<pre class="r"><code>message(&quot;if any values &lt; 0.2 -&gt; possible problem&quot;)
message(&quot;if any values &lt; 0.1 -&gt; definitely a problem&quot;)</code></pre>
<p>In contrast, if we repeat this model for the city centre then we get more substantive results. In this case:</p>
<ul>
<li>the more ships there are, the lower the NO2 at the City Centre site but this is not statistically significant (95% confidence intervals include 0);</li>
<li>compared to the N -&gt; ENE (contrast category omitted from the results), the ENE -&gt; S wind quadrant is associated with nearly 32 times lower NO2 at the City Centre site but this is not statistically significant;</li>
<li>if the wind is ENE -&gt; S then every extra ship increased NO2 at the City Centre site by 7 units and this is statistically significant although the 95% confidence intervals are quite wide (0.993-13.323)</li>
<li>if the wind is in the S -&gt; N quadrant (i.e. the prevailing westerlies) then every extra ship increased NO2 at the City Centre site by 6 units but this is not statistically significant at the 95% level</li>
</ul>
<pre class="r"><code># openair::linearRelation(plotDT, x =&#39;no2_Centre&#39;, y = &#39;no2_A33&#39;)

lmCentre &lt;- lm(no2_Centre ~ allShips * windDir, plotDT)

stargazer::stargazer(lmCentre, type = &quot;text&quot;, title = &quot;Model results&quot;, ci = TRUE, single.row = TRUE)</code></pre>
<pre><code>## 
## Model results
## ========================================================
##                                  Dependent variable:    
##                              ---------------------------
##                                      no2_Centre         
## --------------------------------------------------------
## allShips                       -3.831 (-9.730, 2.068)   
## windDirQ2: ENE -&gt; S           -31.656 (-72.201, 8.889)  
## windDirQ3-4: S -&gt; N           -28.521 (-69.271, 12.228) 
## allShips:windDirQ2: ENE -&gt; S   7.158** (0.993, 13.323)  
## allShips:windDirQ3-4: S -&gt; N   6.005* (-0.481, 12.492)  
## Constant                      40.707** (1.453, 79.961)  
## --------------------------------------------------------
## Observations                             52             
## R2                                      0.406           
## Adjusted R2                             0.342           
## Residual Std. Error                8.359 (df = 46)      
## F Statistic                     6.294*** (df = 5; 46)   
## ========================================================
## Note:                        *p&lt;0.1; **p&lt;0.05; ***p&lt;0.01</code></pre>
<pre class="r"><code># The &#39;car&#39; package has some nice graphs to help here
car::qqPlot(lmCentre)  # shows default 95% CI
car::spreadLevelPlot(lmCentre)
message(&quot;# Do we think the variance of the residuals is constant?&quot;)</code></pre>
<pre class="r"><code>message(&quot;# autocorrelation/independence of errors&quot;)
car::durbinWatsonTest(lmCentre)</code></pre>
<pre><code>##  lag Autocorrelation D-W Statistic p-value
##    1       0.2768075      1.391239   0.006
##  Alternative hypothesis: rho != 0</code></pre>
<pre class="r"><code>message(&quot;# if p &lt; 0.05 then a problem as implies autocorrelation but beware large samples&quot;)</code></pre>
<p>Again however, the durbinWatsonTest test suggests autocorrelation. This means the standard errors are likely to be underestimates and so the confidence intervals are too narrow. As a result effects we think are statistically significant are probably not...</p>
<pre class="r"><code>message(&quot;# homoskedasticity: plot (should be no obvious pattern&quot;)
plot(plotDT[!is.na(no2_Centre)]$no2_Centre, lmCentre$residuals)
abline(h = mean(lmCentre$residuals), col = &quot;red&quot;)  # add the mean of the residuals - ideally 0</code></pre>
<p><img src="sccAirQualExplore_covidLockdown2020_files/figure-html/centreHomoskedasticity-1.png" width="672" /></p>
<pre class="r"><code>message(&quot;# homoskedasticity: formal test&quot;)
car::ncvTest(lmCentre)</code></pre>
<pre><code>## Non-constant Variance Score Test 
## Variance formula: ~ fitted.values 
## Chisquare = 4.111822, Df = 1, p = 0.042584</code></pre>
<pre class="r"><code>message(&quot;# if p &gt; 0.05 then there is heteroskedasticity&quot;)</code></pre>
<pre class="r"><code>message(&quot;# -&gt; collinearity&quot;)
car::vif(lmCentre)</code></pre>
<pre><code>##                       GVIF Df GVIF^(1/(2*Df))
## allShips          22.46581  1        4.739811
## windDir          288.20845  2        4.120280
## allShips:windDir 280.96844  2        4.094156</code></pre>
<pre class="r"><code># if any values &gt; 10 -&gt; problem
message(&quot;# -&gt; tolerance&quot;)
1/car::vif(lmCentre)</code></pre>
<pre><code>##                         GVIF  Df GVIF^(1/(2*Df))
## allShips         0.044512079 1.0       0.2109789
## windDir          0.003469711 0.5       0.2427020
## allShips:windDir 0.003559119 0.5       0.2442506</code></pre>
<pre class="r"><code>message(&quot;# if any values &lt; 0.2 -&gt; possible problem&quot;)
message(&quot;# if any values &lt; 0.1 -&gt; definitely a problem&quot;)</code></pre>
</div>
<div id="summary" class="section level3">
<h3><span class="header-section-number">13.2.5</span> Summary</h3>
<p>Overall while there appear to be correlations between larger numbers of ships and more frequent higher pollution levels under some wind conditions, the small number of observations and possible confounding meteorological effects mean they could just be spurious.</p>
<p>The linear regression model results are indicative of a relationship but suffer from methodological problems (autocorrelation).</p>
<p>We may need a better measure of ship emissions, we need to take out the meteorological effects and we need an approach to time-series regression which can allow for autocorrelaton.</p>
</div>
</div>
<div id="experiments-with-openair" class="section level2">
<h2><span class="header-section-number">13.3</span> Experiments with openair</h2>
<p>The openair R package <span class="citation">(Carslaw and Ropkins 2012)</span> offers a number of pre-formed plot functions which are of potential use.</p>
<pre class="r"><code>cutYear &lt;- 2017  # use as comparison year(s)</code></pre>
<div id="no2-trends-with-theil-sen" class="section level3">
<h3><span class="header-section-number">13.3.1</span> NO2 trends with Theil-Sen</h3>
<p>openair's Theil-Sen function provides de-seasoned trendlines. Figure <a href="#fig:TheilSenNo2Centre">13.25</a> shows the trend for NO2 in Southampton Centre over the last 3 years while Figure <a href="#fig:TheilSenNo2A33">13.26</a> shows the same plot but for the A33 site. Both sites show a faiirly consistent decline over time.</p>
<pre class="r"><code># looking for wide data
no2dt[, `:=`(date, obsDate)]  # set date to date for this one
no2dt[, `:=`(no2, value)]  # looks for named variable

openair::TheilSen(no2dt[site %like% &quot;Centre&quot;], &quot;no2&quot;, ylab = &quot;NO2 (ppb)&quot;, deseason = TRUE, type = c(&quot;site&quot;, &quot;weekday&quot;))</code></pre>
<pre><code>## [1] &quot;Taking bootstrap samples. Please wait.&quot;
## [1] &quot;Taking bootstrap samples. Please wait.&quot;
## [1] &quot;Taking bootstrap samples. Please wait.&quot;
## [1] &quot;Taking bootstrap samples. Please wait.&quot;
## [1] &quot;Taking bootstrap samples. Please wait.&quot;
## [1] &quot;Taking bootstrap samples. Please wait.&quot;
## [1] &quot;Taking bootstrap samples. Please wait.&quot;</code></pre>
<div class="figure"><span id="fig:TheilSenNo2Centre"></span>
<img src="sccAirQualExplore_covidLockdown2020_files/figure-html/TheilSenNo2Centre-1.png" alt="Theil-Sen  plot for NO2 at Southampton Centre, data points are months" width="672" />
<p class="caption">
Figure 13.25: Theil-Sen plot for NO2 at Southampton Centre, data points are months
</p>
</div>
<pre class="r"><code>openair::TheilSen(no2dt[site %like% &quot;A33&quot;], &quot;no2&quot;, ylab = &quot;NO2 (ppb)&quot;, deseason = TRUE, type = c(&quot;site&quot;, &quot;weekday&quot;))</code></pre>
<pre><code>## [1] &quot;Taking bootstrap samples. Please wait.&quot;
## [1] &quot;Taking bootstrap samples. Please wait.&quot;
## [1] &quot;Taking bootstrap samples. Please wait.&quot;
## [1] &quot;Taking bootstrap samples. Please wait.&quot;
## [1] &quot;Taking bootstrap samples. Please wait.&quot;
## [1] &quot;Taking bootstrap samples. Please wait.&quot;
## [1] &quot;Taking bootstrap samples. Please wait.&quot;</code></pre>
<div class="figure"><span id="fig:TheilSenNo2A33"></span>
<img src="sccAirQualExplore_covidLockdown2020_files/figure-html/TheilSenNo2A33-1.png" alt="Theil-Sen  plot by weekday for NO2 at Southampton A33 site, data points are months" width="672" />
<p class="caption">
Figure 13.26: Theil-Sen plot by weekday for NO2 at Southampton A33 site, data points are months
</p>
</div>
</div>
<div id="hour-no2-patterns-with-timevariation" class="section level3">
<h3><span class="header-section-number">13.3.2</span> 24 hour NO2 patterns with timeVariation</h3>
<p>openair's timeVariation function provides plots by time of day and weekday. Figure <a href="#fig:timeVariationNo2Centre">13.27</a> shows the pattern for NO2 in Southampton Centre over the Figure <a href="#fig:timeVariationNo2A33">13.28</a> shows the same plot but for the A33 site. In each case we compare the period before lockdown (from the start of 2017) with the period since lockdown (from 2020-03-24).</p>
<p>These quite clearly show the difference in pollution for pre and during lockdown for specific times of day and days of the week. We can quite clearly see that NO2 has decreased at exactly the times we would expect given the reduction in transport use. This is especially apparent on Mondays and Tuesdays but less obvious on Wednesday to Friday (bottom right plot) with the weekly profile of NO2 emissions looking substantially different.</p>
<pre class="r"><code>no2dt[, `:=`(date, dateTimeUTC)]  # set date to dateTime for this one

no2dt[, `:=`(lockdown, ifelse(dateTimeUTC &lt;= myParams$lockDownStartDate, &quot;Pre lockdown&quot;, &quot;Lockdown&quot;))]

openair::timeVariation(no2dt[site %like% &quot;Centre&quot; &amp; year &gt;= cutYear], &quot;no2&quot;, ylab = &quot;NO2 (ppb)&quot;, group = &quot;lockdown&quot;)</code></pre>
<div class="figure"><span id="fig:timeVariationNo2Centre"></span>
<img src="sccAirQualExplore_covidLockdown2020_files/figure-html/timeVariationNo2Centre-1.png" alt="timeVariation plots for NO2 at Southampton Centre comparing lockdown 2020 with pre-lockdown starting in 2017" width="672" />
<p class="caption">
Figure 13.27: timeVariation plots for NO2 at Southampton Centre comparing lockdown 2020 with pre-lockdown starting in 2017
</p>
</div>
<pre class="r"><code>openair::timeVariation(no2dt[site %like% &quot;A33&quot; &amp; year &gt; cutYear], &quot;no2&quot;, ylab = &quot;NO2 (ppb)&quot;, group = &quot;lockdown&quot;)</code></pre>
<div class="figure"><span id="fig:timeVariationNo2A33"></span>
<img src="sccAirQualExplore_covidLockdown2020_files/figure-html/timeVariationNo2A33-1.png" alt="timeVariation plots for NO2 at Southampton A33 site comparing lockdown 2020 with pre-lockdown starting in 2017" width="672" />
<p class="caption">
Figure 13.28: timeVariation plots for NO2 at Southampton A33 site comparing lockdown 2020 with pre-lockdown starting in 2017
</p>
</div>
</div>
<div id="pm10-trends-with-theil-sen" class="section level3">
<h3><span class="header-section-number">13.3.3</span> PM10 trends with Theil-Sen</h3>
<p>openair's Theil-Sen function provides de-seasoned trendlines. Figure <a href="#fig:TheilSenPM10Centre">13.29</a> shows the trend for PM10 in Southampton Centre over the last 3 years while Figure <a href="#fig:TheilSenPM10A33">13.30</a> shows the same plot but for the A33 site.</p>
<pre class="r"><code>pm10dt[, `:=`(date, obsDate)]
pm10dt[, `:=`(pm10, value)]

openair::TheilSen(pm10dt[site %like% &quot;Centre&quot;], &quot;pm10&quot;, ylab = &quot;PM10&quot;, deseason = TRUE, type = c(&quot;site&quot;, &quot;weekday&quot;))</code></pre>
<pre><code>## [1] &quot;Taking bootstrap samples. Please wait.&quot;
## [1] &quot;Taking bootstrap samples. Please wait.&quot;
## [1] &quot;Taking bootstrap samples. Please wait.&quot;
## [1] &quot;Taking bootstrap samples. Please wait.&quot;
## [1] &quot;Taking bootstrap samples. Please wait.&quot;
## [1] &quot;Taking bootstrap samples. Please wait.&quot;
## [1] &quot;Taking bootstrap samples. Please wait.&quot;</code></pre>
<div class="figure"><span id="fig:TheilSenPM10Centre"></span>
<img src="sccAirQualExplore_covidLockdown2020_files/figure-html/TheilSenPM10Centre-1.png" alt="Theil-Sen  plot for PM10 at Southampton Centre, data points are months" width="672" />
<p class="caption">
Figure 13.29: Theil-Sen plot for PM10 at Southampton Centre, data points are months
</p>
</div>
<pre class="r"><code>openair::TheilSen(pm10dt[site %like% &quot;A33&quot;], &quot;pm10&quot;, ylab = &quot;NO2 (ppb)&quot;, deseason = TRUE, type = c(&quot;site&quot;, &quot;weekday&quot;))</code></pre>
<pre><code>## [1] &quot;Taking bootstrap samples. Please wait.&quot;
## [1] &quot;Taking bootstrap samples. Please wait.&quot;
## [1] &quot;Taking bootstrap samples. Please wait.&quot;
## [1] &quot;Taking bootstrap samples. Please wait.&quot;
## [1] &quot;Taking bootstrap samples. Please wait.&quot;
## [1] &quot;Taking bootstrap samples. Please wait.&quot;
## [1] &quot;Taking bootstrap samples. Please wait.&quot;</code></pre>
<div class="figure"><span id="fig:TheilSenPM10A33"></span>
<img src="sccAirQualExplore_covidLockdown2020_files/figure-html/TheilSenPM10A33-1.png" alt="Theil-Sen  plot by weekday for PM10 at Southampton A33 site, data points are months" width="672" />
<p class="caption">
Figure 13.30: Theil-Sen plot by weekday for PM10 at Southampton A33 site, data points are months
</p>
</div>
</div>
<div id="hour-pm10-patterns-with-timevariation" class="section level3">
<h3><span class="header-section-number">13.3.4</span> 24 hour PM10 patterns with timeVariation</h3>
<p>Figure <a href="#fig:timeVariationPM10Centre">13.31</a> shows the pattern for PM10 in Southampton Centre over the Figure <a href="#fig:timeVariationPM10A33">13.32</a> shows the same plot but for the A33 site. In each case we compare the period before lockdown (from the start of 2017) with the period since lockdown (from 2020-03-24).</p>
<p>Unlike NO2, PM10 has not declined presumably because it is not affected by reduced transport use etc.</p>
<pre class="r"><code>pm10dt[, `:=`(date, dateTimeUTC)]
pm10dt[, `:=`(lockdown, ifelse(dateTimeUTC &lt;= myParams$lockDownStartDate, &quot;Pre lockdown&quot;, &quot;Lockdown&quot;))]

openair::timeVariation(pm10dt[site %like% &quot;Centre&quot; &amp; year &gt;= cutYear], &quot;pm10&quot;, ylab = &quot;PM10&quot;, group = &quot;lockdown&quot;)  # use group to give before/after</code></pre>
<div class="figure"><span id="fig:timeVariationPM10Centre"></span>
<img src="sccAirQualExplore_covidLockdown2020_files/figure-html/timeVariationPM10Centre-1.png" alt="timeVariation plots for PM10 at Southampton Centre comparing lockdown 2020 with pre-lockdown starting in 2017" width="672" />
<p class="caption">
Figure 13.31: timeVariation plots for PM10 at Southampton Centre comparing lockdown 2020 with pre-lockdown starting in 2017
</p>
</div>
<pre class="r"><code>openair::timeVariation(pm10dt[site %like% &quot;A33&quot; &amp; year &gt; cutYear], &quot;pm10&quot;, ylab = &quot;PM10&quot;, group = &quot;lockdown&quot;)</code></pre>
<div class="figure"><span id="fig:timeVariationPM10A33"></span>
<img src="sccAirQualExplore_covidLockdown2020_files/figure-html/timeVariationPM10A33-1.png" alt="timeVariation plots for PM10 at Southampton A33 site comparing lockdown 2020 with pre-lockdown starting in 2017" width="672" />
<p class="caption">
Figure 13.32: timeVariation plots for PM10 at Southampton A33 site comparing lockdown 2020 with pre-lockdown starting in 2017
</p>
</div>
</div>
<div id="pm2.5-trends-with-theil-sen" class="section level3">
<h3><span class="header-section-number">13.3.5</span> PM2.5 trends with Theil-Sen</h3>
<p>openair's Theil-Sen function provides de-seasoned trendlines. Figure <a href="#fig:TheilSenPM25Centre">13.33</a> shows the trend for PM2.5 in Southampton Centre over the last 3 years.</p>
<pre class="r"><code>pm25dt[, `:=`(date, obsDate)]
pm25dt[, `:=`(pm25, value)]

openair::TheilSen(pm25dt[site %like% &quot;Centre&quot;], &quot;pm25&quot;, ylab = &quot;PM2.5&quot;, deseason = TRUE, type = c(&quot;site&quot;, &quot;weekday&quot;))</code></pre>
<pre><code>## [1] &quot;Taking bootstrap samples. Please wait.&quot;
## [1] &quot;Taking bootstrap samples. Please wait.&quot;
## [1] &quot;Taking bootstrap samples. Please wait.&quot;
## [1] &quot;Taking bootstrap samples. Please wait.&quot;
## [1] &quot;Taking bootstrap samples. Please wait.&quot;
## [1] &quot;Taking bootstrap samples. Please wait.&quot;
## [1] &quot;Taking bootstrap samples. Please wait.&quot;</code></pre>
<div class="figure"><span id="fig:TheilSenPM25Centre"></span>
<img src="sccAirQualExplore_covidLockdown2020_files/figure-html/TheilSenPM25Centre-1.png" alt="Theil-Sen  plot for PM2.5 at Southampton Centre, data points are months" width="672" />
<p class="caption">
Figure 13.33: Theil-Sen plot for PM2.5 at Southampton Centre, data points are months
</p>
</div>
</div>
<div id="hour-pm25-patterns-with-timevariation" class="section level3">
<h3><span class="header-section-number">13.3.6</span> 24 hour PM25 patterns with timeVariation</h3>
<p>openair's timeVariation function provides plots by time of day and weekday. Figure <a href="#fig:timeVariationPM25Centre">13.34</a> shows the pattern for PM25 in Southampton Centre. We compare the period before lockdown (from the start of 2019) with the period since lockdown (from 2020-03-24).</p>
<p>As with PM10, PM2.5 has not declined presumably because it is not affected by reduced transport use etc.</p>
<pre class="r"><code>pm25dt[, `:=`(date, dateTimeUTC)]
pm25dt[, `:=`(lockdown, ifelse(dateTimeUTC &lt;= myParams$lockDownStartDate, &quot;Pre lockdown&quot;, &quot;Lockdown&quot;))]

openair::timeVariation(pm25dt[site %like% &quot;Centre&quot; &amp; year &gt;= cutYear], &quot;pm25&quot;, ylab = &quot;PM2.5&quot;, group = &quot;lockdown&quot;)</code></pre>
<div class="figure"><span id="fig:timeVariationPM25Centre"></span>
<img src="sccAirQualExplore_covidLockdown2020_files/figure-html/timeVariationPM25Centre-1.png" alt="timeVariation plots for PM2.5 at Southampton Centre comparing lockdown 2020 with pre-lockdown starting in 2019" width="672" />
<p class="caption">
Figure 13.34: timeVariation plots for PM2.5 at Southampton Centre comparing lockdown 2020 with pre-lockdown starting in 2019
</p>
</div>
</div>
</div>
</div>
<div id="runtime" class="section level1">
<h1><span class="header-section-number">14</span> Runtime</h1>
<p>Report generated using <a href="https://cran.r-project.org/package=knitr">knitr</a> in <a href="http://www.rstudio.com">RStudio</a> with R version 3.6.0 (2019-04-26) running on x86_64-redhat-linux-gnu (#1 SMP Thu May 7 19:30:37 EDT 2020).</p>
<pre class="r"><code>t &lt;- proc.time() - myParams$startTime

elapsed &lt;- t[[3]]</code></pre>
<p>Analysis completed in 151.112 seconds ( 2.52 minutes).</p>
<p>R packages used in this report:</p>
<ul>
<li>data.table - <span class="citation">(Dowle et al. 2015)</span></li>
<li>ggplot2 - <span class="citation">(Wickham 2009)</span></li>
<li>here - <span class="citation">(Müller 2017)</span></li>
<li>kableExtra - <span class="citation">(Zhu 2019)</span></li>
<li>lubridate - <span class="citation">(Grolemund and Wickham 2011)</span></li>
<li>openAir - <span class="citation">(Carslaw and Ropkins 2012)</span></li>
<li>skimr - <span class="citation">(Arino de la Rubia et al. 2017)</span></li>
<li>viridis - <span class="citation">(Garnier 2018)</span></li>
</ul>
</div>
<div id="references" class="section level1 unnumbered">
<h1>References</h1>
<div id="refs" class="references">
<div id="ref-skimr">
<p>Arino de la Rubia, Eduardo, Hao Zhu, Shannon Ellis, Elin Waring, and Michael Quinn. 2017. <em>Skimr: Skimr</em>. <a href="https://github.com/ropenscilabs/skimr" class="uri">https://github.com/ropenscilabs/skimr</a>.</p>
</div>
<div id="ref-openair">
<p>Carslaw, David C., and Karl Ropkins. 2012. “Openair — an R Package for Air Quality Data Analysis.” <em>Environmental Modelling &amp; Software</em> 27–28 (0): 52–61. doi:<a href="https://doi.org/10.1016/j.envsoft.2011.09.008">10.1016/j.envsoft.2011.09.008</a>.</p>
</div>
<div id="ref-data.table">
<p>Dowle, M, A Srinivasan, T Short, S Lianoglou with contributions from R Saporta, and E Antonyan. 2015. <em>Data.table: Extension of Data.frame</em>. <a href="https://CRAN.R-project.org/package=data.table" class="uri">https://CRAN.R-project.org/package=data.table</a>.</p>
</div>
<div id="ref-viridis">
<p>Garnier, Simon. 2018. <em>Viridis: Default Color Maps from ’Matplotlib’</em>. <a href="https://CRAN.R-project.org/package=viridis" class="uri">https://CRAN.R-project.org/package=viridis</a>.</p>
</div>
<div id="ref-lubridate">
<p>Grolemund, Garrett, and Hadley Wickham. 2011. “Dates and Times Made Easy with lubridate.” <em>Journal of Statistical Software</em> 40 (3): 1–25. <a href="http://www.jstatsoft.org/v40/i03/" class="uri">http://www.jstatsoft.org/v40/i03/</a>.</p>
</div>
<div id="ref-here">
<p>Müller, Kirill. 2017. <em>Here: A Simpler Way to Find Your Files</em>. <a href="https://CRAN.R-project.org/package=here" class="uri">https://CRAN.R-project.org/package=here</a>.</p>
</div>
<div id="ref-ggplot2">
<p>Wickham, Hadley. 2009. <em>Ggplot2: Elegant Graphics for Data Analysis</em>. Springer-Verlag New York. <a href="http://ggplot2.org" class="uri">http://ggplot2.org</a>.</p>
</div>
<div id="ref-kableExtra">
<p>Zhu, Hao. 2019. <em>KableExtra: Construct Complex Table with ’Kable’ and Pipe Syntax</em>. <a href="https://CRAN.R-project.org/package=kableExtra" class="uri">https://CRAN.R-project.org/package=kableExtra</a>.</p>
</div>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->
<script>
$(document).ready(function () {
  window.initializeCodeFolding("hide" === "show");
});
</script>

<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
